//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.CreateCustomerLirisProduccion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WSClientes")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GrabarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accountnum {
            get {
                return this.AccountnumField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountnumField, value) != true)) {
                    this.AccountnumField = value;
                    this.RaisePropertyChanged("Accountnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Grabar {
            get {
                return this.GrabarField;
            }
            set {
                if ((this.GrabarField.Equals(value) != true)) {
                    this.GrabarField = value;
                    this.RaisePropertyChanged("Grabar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateCustomerLirisProduccion.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCreate", ReplyAction="http://tempuri.org/IService1/CustomerCreateResponse")]
        POS.CreateCustomerLirisProduccion.Cliente CustomerCreate(string name, string identification, string IdentificationType, string group, string taxGroup, string address, string phone, string country, string state, string city, string currency, string language, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCreate", ReplyAction="http://tempuri.org/IService1/CustomerCreateResponse")]
        System.Threading.Tasks.Task<POS.CreateCustomerLirisProduccion.Cliente> CustomerCreateAsync(string name, string identification, string IdentificationType, string group, string taxGroup, string address, string phone, string country, string state, string city, string currency, string language, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerUpdate", ReplyAction="http://tempuri.org/IService1/CustomerUpdateResponse")]
        bool CustomerUpdate(string identification, string phone, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerUpdate", ReplyAction="http://tempuri.org/IService1/CustomerUpdateResponse")]
        System.Threading.Tasks.Task<bool> CustomerUpdateAsync(string identification, string phone, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCheck", ReplyAction="http://tempuri.org/IService1/CustomerCheckResponse")]
        bool CustomerCheck(string identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCheck", ReplyAction="http://tempuri.org/IService1/CustomerCheckResponse")]
        System.Threading.Tasks.Task<bool> CustomerCheckAsync(string identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IdentificationValidate", ReplyAction="http://tempuri.org/IService1/IdentificationValidateResponse")]
        bool IdentificationValidate(string value, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IdentificationValidate", ReplyAction="http://tempuri.org/IService1/IdentificationValidateResponse")]
        System.Threading.Tasks.Task<bool> IdentificationValidateAsync(string value, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistraPagoPAVIPLAN", ReplyAction="http://tempuri.org/IService1/RegistraPagoPAVIPLANResponse")]
        bool RegistraPagoPAVIPLAN(string cliente, string local, float monto, string forma, string detalle, string cajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistraPagoPAVIPLAN", ReplyAction="http://tempuri.org/IService1/RegistraPagoPAVIPLANResponse")]
        System.Threading.Tasks.Task<bool> RegistraPagoPAVIPLANAsync(string cliente, string local, float monto, string forma, string detalle, string cajero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : POS.CreateCustomerLirisProduccion.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<POS.CreateCustomerLirisProduccion.IService1>, POS.CreateCustomerLirisProduccion.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public POS.CreateCustomerLirisProduccion.Cliente CustomerCreate(string name, string identification, string IdentificationType, string group, string taxGroup, string address, string phone, string country, string state, string city, string currency, string language, string correo) {
            return base.Channel.CustomerCreate(name, identification, IdentificationType, group, taxGroup, address, phone, country, state, city, currency, language, correo);
        }
        
        public System.Threading.Tasks.Task<POS.CreateCustomerLirisProduccion.Cliente> CustomerCreateAsync(string name, string identification, string IdentificationType, string group, string taxGroup, string address, string phone, string country, string state, string city, string currency, string language, string correo) {
            return base.Channel.CustomerCreateAsync(name, identification, IdentificationType, group, taxGroup, address, phone, country, state, city, currency, language, correo);
        }
        
        public bool CustomerUpdate(string identification, string phone, string correo) {
            return base.Channel.CustomerUpdate(identification, phone, correo);
        }
        
        public System.Threading.Tasks.Task<bool> CustomerUpdateAsync(string identification, string phone, string correo) {
            return base.Channel.CustomerUpdateAsync(identification, phone, correo);
        }
        
        public bool CustomerCheck(string identification) {
            return base.Channel.CustomerCheck(identification);
        }
        
        public System.Threading.Tasks.Task<bool> CustomerCheckAsync(string identification) {
            return base.Channel.CustomerCheckAsync(identification);
        }
        
        public bool IdentificationValidate(string value, string type) {
            return base.Channel.IdentificationValidate(value, type);
        }
        
        public System.Threading.Tasks.Task<bool> IdentificationValidateAsync(string value, string type) {
            return base.Channel.IdentificationValidateAsync(value, type);
        }
        
        public bool RegistraPagoPAVIPLAN(string cliente, string local, float monto, string forma, string detalle, string cajero) {
            return base.Channel.RegistraPagoPAVIPLAN(cliente, local, monto, forma, detalle, cajero);
        }
        
        public System.Threading.Tasks.Task<bool> RegistraPagoPAVIPLANAsync(string cliente, string local, float monto, string forma, string detalle, string cajero) {
            return base.Channel.RegistraPagoPAVIPLANAsync(cliente, local, monto, forma, detalle, cajero);
        }
    }
}
