//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ax_viewConsumoCreditoCliente2
    {
        public string ACCOUNTNUM { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public int CORTE { get; set; }
    }
}
