//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ax_viewConsumoCreditoCliente
    {
        public string ACCOUNTNUM { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public int CORTE { get; set; }
    }
}
