//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_Apertura
    {
        public string CEDULA { get; set; }
        public string CAJERA { get; set; }
        public string LOCAL { get; set; }
        public string PUNTO_VENTA { get; set; }
        public string TURNO { get; set; }
        public decimal VALOR_BASE { get; set; }
        public string ESTABLECIMIENTO { get; set; }
        public string PUNTO_EMISION { get; set; }
        public string IP { get; set; }
        public System.DateTime FECHA { get; set; }
        public int LEIDO { get; set; }
        public int NUM_CAJA { get; set; }
        public int CERRADO { get; set; }
        public int PRE_CIERRE { get; set; }
        public string INVENTLOCATION { get; set; }
        public string ID_CAJA { get; set; }
    }
}
