//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_Lst_POS_no_sub_AX
    {
        public string establecimiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string orderID { get; set; }
        public string item_id { get; set; }
        public string item_nombre { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> unidades { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
