
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_puntoemision
{

    public core_puntoemision()
    {

        this.core_documentosecuencia = new HashSet<core_documentosecuencia>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string establecimiento_id { get; set; }

    public string punto_emision { get; set; }

    public string ip_address { get; set; }

    public bool activo { get; set; }

    public int secuencia_broadnet { get; set; }

    public string TID { get; set; }

    public bool usa_balanza { get; set; }

    public bool scanner_integrado { get; set; }

    public string marca_balanza { get; set; }

    public string puerto_balanza { get; set; }

    public string TID_DATAFAST { get; set; }

    public int secuencia_datafast { get; set; }

    public int lote_medianet { get; set; }

    public int lote_datafast { get; set; }

    public int puerto_pinpad { get; set; }

    public string ModeloBalanza { get; set; }

    public string IpPinpad { get; set; }

    public bool EsTcipPinpad { get; set; }



    public virtual ICollection<core_documentosecuencia> core_documentosecuencia { get; set; }

    public virtual core_establecimiento core_establecimiento { get; set; }

}

}
