//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_factura_view
    {
        public int id { get; set; }
        public System.DateTime DateInvoice { get; set; }
        public string InvoiceId { get; set; }
        public string InvoiceAccount { get; set; }
        public string Address { get; set; }
        public string SalesResponsable { get; set; }
        public string InventLocationId { get; set; }
        public string documento { get; set; }
        public decimal descuento { get; set; }
        public decimal descuento2 { get; set; }
        public string orderID { get; set; }
        public bool loadinvoice { get; set; }
        public Nullable<decimal> SalesSubtotal { get; set; }
    }
}
