
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_facturapago_view
{

    public int id { get; set; }

    public string InvoiceId { get; set; }

    public string Paymode { get; set; }

    public string InvoiceAccount { get; set; }

    public string PayReference { get; set; }

    public decimal Amount { get; set; }

    public System.DateTime PaymDate { get; set; }

    public int PaymID { get; set; }

    public string documento { get; set; }

    public string Voucher { get; set; }

}

}
