
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_tarjetacreditointerno
{

    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public int empresa_id { get; set; }

    public string codigo { get; set; }

    public string identificacion { get; set; }

    public string nombre_tarjeta { get; set; }

    public Nullable<System.DateTime> fecha_activacion { get; set; }

    public Nullable<System.DateTime> fecha_expiracion { get; set; }

    public Nullable<System.DateTime> fecha_desactivacion { get; set; }

    public decimal saldo { get; set; }

    public bool activo { get; set; }

    public Nullable<decimal> cupo { get; set; }

    public string identificacionPrincipal { get; set; }



    public virtual core_empresacredito core_empresacredito { get; set; }

}

}
