//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_factura1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public core_factura1()
        {
            this.core_facturapago = new HashSet<core_facturapago1>();
            this.core_facturadetalle = new HashSet<core_facturadetalle1>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public long numero { get; set; }
        public string documento { get; set; }
        public string cliente_ax { get; set; }
        public string cliente { get; set; }
        public string razon_social { get; set; }
        public string direccion { get; set; }
        public decimal base0 { get; set; }
        public decimal base12 { get; set; }
        public decimal subtotal { get; set; }
        public decimal descuento { get; set; }
        public decimal descuento2 { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public string autorizacion { get; set; }
        public string ip { get; set; }
        public string usuario { get; set; }
        public string orderID { get; set; }
        public bool loadinvoice { get; set; }
        public bool loadpaym { get; set; }
        public string msgError { get; set; }
        public string paymID { get; set; }
        public decimal descuentoPorc { get; set; }
        public string Observacion { get; set; }
        public string direccionEntrega { get; set; }
        public Nullable<int> orderApp { get; set; }
        public Nullable<bool> pedidoProgramado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_facturapago1> core_facturapago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_facturadetalle1> core_facturadetalle { get; set; }
    }
}
