//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_facturapagoAPP1
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int factura_id { get; set; }
        public string tipo_id { get; set; }
        public decimal valor { get; set; }
        public string cliente { get; set; }
        public string datos { get; set; }
        public string JournalNum { get; set; }
        public string voucher { get; set; }
    }
}
