//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_tarjetacredito_bin
    {
        public int id { get; set; }
        public string bin { get; set; }
        public string bin_descripcion { get; set; }
        public string bin_red { get; set; }
        public string bin_red_cred { get; set; }
    }
}
