//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_secuenciaAnuladaNC
    {
        public int Id { get; set; }
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public Nullable<long> numero { get; set; }
        public string descripcion { get; set; }
    }
}
