//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_tarjetacredito_binCom
    {
        public int id { get; set; }
        public string bin { get; set; }
        public string bin_descripcion { get; set; }
        public string bin_red { get; set; }
        public string bin_red_cred { get; set; }
        public string Marca { get; set; }
        public string Producto { get; set; }
    }
}
