
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_documento
{

    public core_documento()
    {

        this.core_documentosecuencia = new HashSet<core_documentosecuencia>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string descripcion { get; set; }

    public string codigo { get; set; }



    public virtual ICollection<core_documentosecuencia> core_documentosecuencia { get; set; }

}

}
