
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_TarjetaDescuentoHistorico
{

    public int id { get; set; }

    public System.DateTime fecha_Transaccion { get; set; }

    public string codigoTarjeta { get; set; }

    public string num_factura { get; set; }

    public decimal valorDescuento { get; set; }

}

}
