//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_facturadetalle1
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int factura_id { get; set; }
        public int linea { get; set; }
        public string item_id { get; set; }
        public string item_nombre { get; set; }
        public decimal cantidad { get; set; }
        public decimal unidades { get; set; }
        public decimal subtotal { get; set; }
        public decimal descuento { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public string unidad { get; set; }
        public decimal costo { get; set; }
        public decimal precio { get; set; }
        public string Observacion { get; set; }
    
        public virtual core_factura1 core_factura { get; set; }
    }
}
