
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_empresacreditopago
{

    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public int codigo_id { get; set; }

    public string tipo_pago { get; set; }

    public string comentario { get; set; }

    public decimal valor { get; set; }

    public string estado { get; set; }



    public virtual core_empresacreditocorte core_empresacreditocorte { get; set; }

}

}
