
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_transaccion_operador
{

    public int id { get; set; }

    public int factura_detalle_id { get; set; }

    public string operador { get; set; }

    public System.DateTime fecha { get; set; }



    public virtual core_facturadetalle core_facturadetalle { get; set; }

}

}
