
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_facturadetalle_view
{

    public int id { get; set; }

    public string InvoiceId { get; set; }

    public string itemid { get; set; }

    public string description { get; set; }

    public int LineNum { get; set; }

    public decimal SalesQTY { get; set; }

    public decimal SalesPrice { get; set; }

    public decimal SalesDesc { get; set; }

    public string SalesUnit { get; set; }

    public Nullable<decimal> LineAmount { get; set; }

    public int TAX { get; set; }

    public Nullable<decimal> SalesDescUnit { get; set; }

}

}
