
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_ClaveAccesoFE
{

    public int Id { get; set; }

    public int FacturaId { get; set; }

    public string ClaveAcceso { get; set; }



    public virtual core_factura core_factura { get; set; }

}

}
