
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_empresacreditocorte
{

    public core_empresacreditocorte()
    {

        this.core_empresacreditopago = new HashSet<core_empresacreditopago>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public int codigo_id { get; set; }

    public System.DateTime fecha_inicio { get; set; }

    public System.DateTime fecha_fin { get; set; }

    public decimal monto { get; set; }

    public int estado { get; set; }



    public virtual core_empresacredito core_empresacredito { get; set; }

    public virtual ICollection<core_empresacreditopago> core_empresacreditopago { get; set; }

}

}
