
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_facturadetalle
{

    public core_facturadetalle()
    {

        this.core_transaccion_operador = new HashSet<core_transaccion_operador>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public int factura_id { get; set; }

    public int linea { get; set; }

    public string item_id { get; set; }

    public string item_nombre { get; set; }

    public decimal cantidad { get; set; }

    public decimal unidades { get; set; }

    public decimal subtotal { get; set; }

    public decimal descuento { get; set; }

    public decimal iva { get; set; }

    public decimal total { get; set; }

    public string unidad { get; set; }

    public decimal costo { get; set; }

    public decimal precio { get; set; }



    public virtual core_factura core_factura { get; set; }

    public virtual ICollection<core_transaccion_operador> core_transaccion_operador { get; set; }

}

}
