
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_retencion
{

    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public System.DateTime fecha_autorizacion { get; set; }

    public int factura_id { get; set; }

    public string num_retencion { get; set; }

    public string num_autorizacion { get; set; }

    public string num_factura { get; set; }

    public decimal valor_ret_fte { get; set; }

    public decimal valor_base { get; set; }

    public string CodRetIVA { get; set; }

    public decimal CodPorcRetIVA { get; set; }

    public decimal ValorBaseIVA { get; set; }

    public decimal ValorRetIVA { get; set; }

    public string ConceptoRetIVA { get; set; }

    public Nullable<byte> TipoRetencion { get; set; }

    public string UsuarioCreacion { get; set; }

    public string UsuarioModifica { get; set; }

    public string Cliente { get; set; }

    public string Establecimiento { get; set; }

    public string PuntoEmision { get; set; }

    public Nullable<byte> Procesado { get; set; }

    public string JournalNum { get; set; }

    public string ID_Caja { get; set; }

    public Nullable<decimal> valor_ret_fte175 { get; set; }

    public Nullable<decimal> valor_base175 { get; set; }

    public Nullable<decimal> valor_base1 { get; set; }



    public virtual core_factura core_factura { get; set; }

}

}
