
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_facturaAPP
{

    public core_facturaAPP()
    {

        this.core_facturapagoAPP = new HashSet<core_facturapagoAPP>();

        this.core_facturadetalleAPP = new HashSet<core_facturadetalleAPP>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string establecimiento { get; set; }

    public string punto_emision { get; set; }

    public long numero { get; set; }

    public string documento { get; set; }

    public string cliente_ax { get; set; }

    public string cliente { get; set; }

    public string razon_social { get; set; }

    public string direccion { get; set; }

    public decimal base0 { get; set; }

    public decimal base12 { get; set; }

    public decimal subtotal { get; set; }

    public decimal descuento { get; set; }

    public decimal descuento2 { get; set; }

    public decimal iva { get; set; }

    public decimal total { get; set; }

    public string autorizacion { get; set; }

    public string ip { get; set; }

    public string usuario { get; set; }

    public string orderID { get; set; }

    public bool loadinvoice { get; set; }

    public bool loadpaym { get; set; }

    public string msgError { get; set; }

    public string paymID { get; set; }

    public decimal descuentoPorc { get; set; }

    public string Observacion { get; set; }

    public string direccionEntrega { get; set; }

    public Nullable<int> orderApp { get; set; }

    public Nullable<bool> pedidoProgramado { get; set; }

    public Nullable<byte> turno { get; set; }



    public virtual ICollection<core_facturapagoAPP> core_facturapagoAPP { get; set; }

    public virtual ICollection<core_facturadetalleAPP> core_facturadetalleAPP { get; set; }

}

}
