
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_promocionticket
{

    public core_promocionticket()
    {

        this.isgiftcard = false;

        this.valor_giftcard = 0m;

        this.core_tarjetacreditopromocionticket = new HashSet<core_tarjetacreditopromocionticket>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public System.DateTime fecha_desde { get; set; }

    public System.DateTime fecha_hasta { get; set; }

    public decimal valor { get; set; }

    public string descripcion { get; set; }

    public string descripcion_larga { get; set; }

    public string establecimiento { get; set; }

    public bool impresion_unitario { get; set; }

    public string division { get; set; }

    public Nullable<bool> ismoneda { get; set; }

    public Nullable<bool> isgiftcard { get; set; }

    public Nullable<decimal> valor_giftcard { get; set; }

    public Nullable<bool> requiereProducto { get; set; }

    public Nullable<int> productoCantidad { get; set; }



    public virtual ICollection<core_tarjetacreditopromocionticket> core_tarjetacreditopromocionticket { get; set; }

}

}
