
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_promocompragratis
{

    public int id { get; set; }

    public string Local { get; set; }

    public System.DateTime fecha { get; set; }

    public decimal TotalFacDesde { get; set; }

    public decimal TotalFacHasta { get; set; }

    public decimal Cantidad { get; set; }

    public decimal Entregado { get; set; }

}

}
