
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_giftcard
{

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string codigo { get; set; }

    public Nullable<System.DateTime> fecha_activacion { get; set; }

    public Nullable<System.DateTime> fecha_expiracion { get; set; }

    public Nullable<System.DateTime> fecha_desactivacion { get; set; }

    public decimal saldo { get; set; }

    public bool activo { get; set; }

    public bool bono { get; set; }

    public Nullable<decimal> valor { get; set; }

    public Nullable<byte> tipo { get; set; }

    public Nullable<short> IdGrupoCliente { get; set; }

    public decimal monto { get; set; }

    public string tipoTransaccion { get; set; }

    public Nullable<byte> tipoTransaccionId { get; set; }

}

}
