//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_facturapagoAPP
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int factura_id { get; set; }
        public string tipo_id { get; set; }
        public decimal valor { get; set; }
        public string cliente { get; set; }
        public string datos { get; set; }
        public string JournalNum { get; set; }
        public string voucher { get; set; }
    
        public virtual core_facturaAPP core_facturaAPP { get; set; }
    }
}
