
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_empresacredito
{

    public core_empresacredito()
    {

        this.core_empresacreditocorte = new HashSet<core_empresacreditocorte>();

        this.core_tarjetacreditointerno = new HashSet<core_tarjetacreditointerno>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string codigo { get; set; }

    public string razon_social { get; set; }

    public bool lista_blanca { get; set; }

    public int dia_corte { get; set; }



    public virtual ICollection<core_empresacreditocorte> core_empresacreditocorte { get; set; }

    public virtual ICollection<core_tarjetacreditointerno> core_tarjetacreditointerno { get; set; }

}

}
