//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_notacreditodetalle
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int notacredito_id { get; set; }
        public int linea { get; set; }
        public string item_id { get; set; }
        public decimal cantidad { get; set; }
        public decimal pvp { get; set; }
        public decimal descuento { get; set; }
        public string unidad { get; set; }
        public decimal total { get; set; }
    
        public virtual core_notacredito core_notacredito { get; set; }
    }
}
