
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_establecimiento
{

    public core_establecimiento()
    {

        this.core_puntoemision = new HashSet<core_puntoemision>();

    }


    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string establecimiento { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string administrador { get; set; }

    public string administrador_email { get; set; }

    public string MID { get; set; }

    public string almacen { get; set; }



    public virtual ICollection<core_puntoemision> core_puntoemision { get; set; }

}

}
