//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_descuento
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string descripcion { get; set; }
        public decimal valor { get; set; }
        public string tipo_descuento { get; set; }
        public string parametro { get; set; }
        public string parametro2 { get; set; }
        public bool rango_fecha { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public bool usar_dia_semana { get; set; }
        public Nullable<int> dia_semana { get; set; }
        public bool activo { get; set; }
    }
}
