
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_notacredito
{

    public core_notacredito()
    {

        this.core_notacreditodetalle = new HashSet<core_notacreditodetalle>();

    }


    public int id { get; set; }

    public System.DateTime fecha { get; set; }

    public string numdocumento { get; set; }

    public string documentoaplica { get; set; }

    public string motivo { get; set; }

    public string cliente { get; set; }

    public decimal valor { get; set; }

    public string usuario { get; set; }

    public string salesID { get; set; }

    public bool loadinvoice { get; set; }

    public bool loadpaym { get; set; }

    public string msgError { get; set; }

    public string paymID { get; set; }

    public string ClaveAccesoSRI { get; set; }



    public virtual ICollection<core_notacreditodetalle> core_notacreditodetalle { get; set; }

}

}
