
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_tarjetacredito
{

    public core_tarjetacredito()
    {

        this.core_tarjetacreditopromocionticket = new HashSet<core_tarjetacreditopromocionticket>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public int banco_id { get; set; }

    public string nombre { get; set; }

    public string tipo { get; set; }

    public int operador { get; set; }



    public virtual core_banco core_banco { get; set; }

    public virtual ICollection<core_tarjetacreditopromocionticket> core_tarjetacreditopromocionticket { get; set; }

}

}
