
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_tarjetacreditopromocionticket
{

    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public int promocion_id { get; set; }

    public int tarjeta_id { get; set; }

    public int multiplicador { get; set; }



    public virtual core_promocionticket core_promocionticket { get; set; }

    public virtual core_tarjetacredito core_tarjetacredito { get; set; }

}

}
