
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Core_CargaDocumento
{

    public int Id { get; set; }

    public int Retencion_Id { get; set; }

    public string UsuarioCreacion { get; set; }

    public string Documento { get; set; }

    public string IdCaja { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioModifica { get; set; }

    public Nullable<System.DateTime> FechaModifcacion { get; set; }

    public short Procesado { get; set; }

}

}
