//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Renta
    {
        public int id { get; set; }
        public string Identifiacion { get; set; }
        public string Nombres { get; set; }
        public decimal Valor { get; set; }
        public string Cuenta { get; set; }
        public string Dep { get; set; }
        public string Cent { get; set; }
        public string Prop { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string usuarioCrecion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string usuarioModifica { get; set; }
    }
}
