//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_DocumentoSecuenciaAPP
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int documento_id { get; set; }
        public int punto_emision_id { get; set; }
        public long siguiente { get; set; }
    
        public virtual core_puntoemision core_puntoemision { get; set; }
        public virtual core_documento core_documento { get; set; }
    }
}
