
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class core_banco
{

    public core_banco()
    {

        this.core_tarjetacredito = new HashSet<core_tarjetacredito>();

    }


    public int id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

    public string nombre { get; set; }



    public virtual ICollection<core_tarjetacredito> core_tarjetacredito { get; set; }

}

}
