//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_FranjaHoraria
    {
        public Nullable<int> Turno { get; set; }
        public string Almacen { get; set; }
        public string Descripcion { get; set; }
        public System.TimeSpan HoraDesde { get; set; }
        public System.TimeSpan HoraHasta { get; set; }
        public bool Estado { get; set; }
    }
}
