//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_documentosecuencia
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int documento_id { get; set; }
        public int punto_emision_id { get; set; }
        public long siguiente { get; set; }
    
        public virtual core_documento core_documento { get; set; }
        public virtual core_puntoemision core_puntoemision { get; set; }
    }
}
