//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_ordendetalle
    {
        public long id { get; set; }
        public long cp_id { get; set; }
        public string numOrder { get; set; }
        public string codigo { get; set; }
        public decimal cantidad { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual cp_ordencabecera cp_ordencabecera { get; set; }
    }
}
