
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class django_content_type
{

    public django_content_type()
    {

        this.auth_permission = new HashSet<auth_permission>();

        this.django_admin_log = new HashSet<django_admin_log>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string app_label { get; set; }

    public string model { get; set; }



    public virtual ICollection<auth_permission> auth_permission { get; set; }

    public virtual ICollection<django_admin_log> django_admin_log { get; set; }

}

}
