
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LstCampania
{

    public LstCampania()
    {

        this.LstCampaniaDet = new HashSet<LstCampaniaDet>();

        this.LstCampaniaEstablecimientos = new HashSet<LstCampaniaEstablecimientos>();

        this.TblPuntos = new HashSet<TblPuntos>();

    }


    public int IdLstCampania { get; set; }

    public string Descripcion { get; set; }

    public Nullable<short> DiasVigencia { get; set; }

    public Nullable<System.DateTime> FechaDesde { get; set; }

    public Nullable<System.DateTime> FechaHasta { get; set; }

    public bool Estado { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public string UsuarioModifica { get; set; }



    public virtual ICollection<LstCampaniaDet> LstCampaniaDet { get; set; }

    public virtual ICollection<LstCampaniaEstablecimientos> LstCampaniaEstablecimientos { get; set; }

    public virtual ICollection<TblPuntos> TblPuntos { get; set; }

}

}
