
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LstCampaniaDet
{

    public int IdLstCampaniaDet { get; set; }

    public int IdLstCampania { get; set; }

    public string Proveedor { get; set; }

    public string SubGrupo { get; set; }

    public string Producto { get; set; }

    public string FormaPago { get; set; }

    public string ValorFormaPago { get; set; }

    public Nullable<decimal> ValorMinCompra { get; set; }

    public Nullable<decimal> FactorPuntos { get; set; }

    public Nullable<System.DateTime> FechaDesde { get; set; }

    public Nullable<System.DateTime> FechaHasta { get; set; }

    public Nullable<bool> Estado { get; set; }



    public virtual LstCampania LstCampania { get; set; }

}

}
