
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LstDelivery
{

    public LstDelivery()
    {

        this.TblOrdenDelivery = new HashSet<TblOrdenDelivery>();

    }


    public int Id { get; set; }

    public string Nombre { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public byte Estado { get; set; }



    public virtual ICollection<TblOrdenDelivery> TblOrdenDelivery { get; set; }

}

}
