
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LstEncuestaEstablecimiento
{

    public short IdEncuestaEstablecimiento { get; set; }

    public short IdEncuesta { get; set; }

    public string Establecimiento { get; set; }

    public bool Estado { get; set; }



    public virtual LstEncuesta LstEncuesta { get; set; }

}

}
