
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LstEncuesta
{

    public LstEncuesta()
    {

        this.LstEncuestaEstablecimiento = new HashSet<LstEncuestaEstablecimiento>();

        this.LstPregunta = new HashSet<LstPregunta>();

        this.TblEncuestaRealizada = new HashSet<TblEncuestaRealizada>();

    }


    public short IdEncuesta { get; set; }

    public bool EsAplicaTodos { get; set; }

    public System.DateTime FechaDesde { get; set; }

    public System.DateTime FechaHasta { get; set; }

    public bool Estado { get; set; }

    public string Descripcion { get; set; }

    public bool PermiteAbandonar { get; set; }



    public virtual ICollection<LstEncuestaEstablecimiento> LstEncuestaEstablecimiento { get; set; }

    public virtual ICollection<LstPregunta> LstPregunta { get; set; }

    public virtual ICollection<TblEncuestaRealizada> TblEncuestaRealizada { get; set; }

}

}
