//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstOpcionesRespuesta
    {
        public short IdOpcionRespuesta { get; set; }
        public short IdPregunta { get; set; }
        public bool Estado { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> OrdenPreguntaSig { get; set; }
    
        public virtual LstPregunta LstPregunta { get; set; }
    }
}
