
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LstPregunta
{

    public LstPregunta()
    {

        this.LstOpcionesRespuesta = new HashSet<LstOpcionesRespuesta>();

        this.TblEncuestaDetalle = new HashSet<TblEncuestaDetalle>();

    }


    public short IdPregunta { get; set; }

    public short IdEncuesta { get; set; }

    public byte TipoPregunta { get; set; }

    public bool Estado { get; set; }

    public string Descripcion { get; set; }

    public byte Orden { get; set; }



    public virtual LstEncuesta LstEncuesta { get; set; }

    public virtual ICollection<LstOpcionesRespuesta> LstOpcionesRespuesta { get; set; }

    public virtual ICollection<TblEncuestaDetalle> TblEncuestaDetalle { get; set; }

}

}
