//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstProductosCanjear
    {
        public LstProductosCanjear()
        {
            this.LstProductosCanjearDet = new HashSet<LstProductosCanjearDet>();
        }
    
        public int IdLstPagosPuntos { get; set; }
        public int IdLstCampania { get; set; }
        public byte Tipo { get; set; }
        public string Valor { get; set; }
        public decimal Puntos { get; set; }
        public bool EsInventario { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<LstProductosCanjearDet> LstProductosCanjearDet { get; set; }
    }
}
