//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstProductosCanjearDet
    {
        public int IdLstProductosCanjearDet { get; set; }
        public int IdLstPagosPuntos { get; set; }
        public string Establecimiento { get; set; }
        public string Producto { get; set; }
        public decimal Stock { get; set; }
        public decimal Disponible { get; set; }
        public bool Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public decimal Puntos { get; set; }
    
        public virtual LstProductosCanjear LstProductosCanjear { get; set; }
    }
}
