
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mt_FacturasRezagadas
{

    public long id { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public string establecimiento { get; set; }

    public string punto_emision { get; set; }

    public long numero { get; set; }

    public string cliente_ax { get; set; }

    public decimal total { get; set; }

    public short estado { get; set; }

    public System.DateTime fecha_deteccion { get; set; }

    public Nullable<System.DateTime> fecha_correccion { get; set; }

}

}
