//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_customer
    {
        public string ACCOUNTNUM { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string TELEFAX { get; set; }
        public string CUSTGROUP { get; set; }
        public decimal CREDITMAX { get; set; }
        public int MANDATORYCREDITLIMIT { get; set; }
        public string DIMENSION { get; set; }
        public string DIMENSION2_ { get; set; }
        public string DIMENSION3_ { get; set; }
        public string VATNUM { get; set; }
        public string COUNTRYREGIONID { get; set; }
        public string EMAIL { get; set; }
        public string CELLULARPHONE { get; set; }
        public string PHONELOCAL { get; set; }
        public string STREET { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public string DATAAREAID { get; set; }
        public long RECID { get; set; }
    }
}
