//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_item_orden
    {
        public string ITEMID { get; set; }
        public string CATEGORIA { get; set; }
        public string ESTABLECIMIENTO { get; set; }
        public int ORDEN { get; set; }
    }
}
