
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class POS_VOUCHER
{

    public long id { get; set; }

    public string TARJETA { get; set; }

    public string CODIGOPROCESO { get; set; }

    public string FECHACONSUMO { get; set; }

    public string HORACONSUMO { get; set; }

    public string NUMEROVOUCHER { get; set; }

    public string AUTORIZACION { get; set; }

    public string VALORCONSUMO { get; set; }

    public string FORMAAUTORIZA { get; set; }

    public string TIPOCONSUMO { get; set; }

    public string PLAZO { get; set; }

    public string TIPOLECTURA { get; set; }

    public string TIPOMONEDA { get; set; }

    public string VALORIVA { get; set; }

    public string VALORSERVICIO { get; set; }

    public string VALORPROPINA { get; set; }

    public string VALORINTERES { get; set; }

    public string VALORFIJO { get; set; }

    public string TIPOPROMOCION { get; set; }

    public string MESESGRACIA { get; set; }

    public string EMPRESASERVICIO { get; set; }

    public string ESTADOTRX { get; set; }

    public string CODIGORESPUESTA { get; set; }

    public string TIPODISPOSITIVO { get; set; }

    public string ADQUIRENTETARJETA { get; set; }

    public string ADQUIRENTESERVICIO { get; set; }

    public string MONTOGRAVAIVA { get; set; }

    public string MONTONOGRAVAIVA { get; set; }

    public string PUNTOEMISION { get; set; }

    public bool PROCESADO { get; set; }

    public string GRUPOTAR { get; set; }

    public int AUTORIZADOR { get; set; }

    public string LOTE { get; set; }

    public bool ANULADO { get; set; }

    public bool PROCESADOTURNO { get; set; }

    public string FACTURA { get; set; }

    public string ARQC { get; set; }

    public string AIDEMV { get; set; }

    public string EMV { get; set; }

    public string TC { get; set; }

    public string PUBLICIDAD { get; set; }

    public string TIPOTRANSACCION { get; set; }

    public string BANCOADQUIRIENTE { get; set; }

    public string TARJETAHABIENTE { get; set; }

    public string MID { get; set; }

    public string TID { get; set; }

    public string VENCTAR { get; set; }

    public string ANULAUTORIZACION { get; set; }

    public string TIPOBANCOTARJETA { get; set; }

}

}
