//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_itembarra_bg
    {
        public long RECID { get; set; }
        public string ITEMBARCODE { get; set; }
        public string ITEMID { get; set; }
        public string INVENTDIMID { get; set; }
        public string BARCODESETUPID { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public int DEL_MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public string DATAAREAID { get; set; }
    }
}
