
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class pos_itembarra_desc
{

    public long ID { get; set; }

    public string ITEMBARCODE { get; set; }

    public string FACTURA { get; set; }

    public Nullable<bool> FACTURADO { get; set; }

}

}
