
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class pos_tarjeta_tipopago
{

    public string IdPago { get; set; }

    public string NombreTipoPago { get; set; }

    public bool Estado { get; set; }

    public string idTipo { get; set; }

    public string tipoConsumo { get; set; }

    public string tipoConsumoData { get; set; }

}

}
