
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class pos_item
{

    public string ITEMGROUPID { get; set; }

    public string ITEMID { get; set; }

    public string ITEMNAME { get; set; }

    public string PRIMARYVENDORID { get; set; }

    public string NAMEALIAS { get; set; }

    public string DATAAREAID { get; set; }

    public decimal TAXVALUE { get; set; }

    public decimal COST { get; set; }

    public Nullable<decimal> PRICE { get; set; }

    public string UNITID { get; set; }

    public int ITEMTYPE { get; set; }

    public int BLOQUEADOPOS { get; set; }

    public string categoria { get; set; }

    public Nullable<decimal> retporc { get; set; }

    public string VARIEDAD { get; set; }

    public string SUBGRUPO { get; set; }

    public string GRUPO { get; set; }

    public Nullable<bool> estado { get; set; }

}

}
