
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class pos_autorizacionsri
{

    public string autorizacion { get; set; }

    public System.DateTime fecha_inicio { get; set; }

    public System.DateTime fecha_fin { get; set; }

    public bool activo { get; set; }

}

}
