

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class POSEntities : DbContext
{
    //public POSEntities()
    //    : base("name=POSEntities")
    //{

    //}

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<pos_customer> pos_customer { get; set; }

    public DbSet<pos_itembarra> pos_itembarra { get; set; }

    public DbSet<core_documento> core_documento { get; set; }

    public DbSet<core_documentosecuencia> core_documentosecuencia { get; set; }

    public DbSet<core_establecimiento> core_establecimiento { get; set; }

    public DbSet<core_puntoemision> core_puntoemision { get; set; }

    public DbSet<core_banco> core_banco { get; set; }

    public DbSet<core_tarjetacredito> core_tarjetacredito { get; set; }

    public DbSet<core_giftcardtransaccion> core_giftcardtransaccion { get; set; }

    public DbSet<core_factura> core_factura { get; set; }

    public DbSet<core_facturadetalle> core_facturadetalle { get; set; }

    public DbSet<core_facturapago> core_facturapago { get; set; }

    public DbSet<pos_paymentmode> pos_paymentmode { get; set; }

    public DbSet<core_autorizacionsri> core_autorizacionsri { get; set; }

    public DbSet<core_parametro> core_parametro { get; set; }

    public DbSet<core_recibo> core_recibo { get; set; }

    public DbSet<core_tarjetacreditointerno> core_tarjetacreditointerno { get; set; }

    public DbSet<core_tarjetacreditointernotransaccion> core_tarjetacreditointernotransaccion { get; set; }

    public DbSet<core_promocionticket> core_promocionticket { get; set; }

    public DbSet<core_tarjetacreditopromocionticket> core_tarjetacreditopromocionticket { get; set; }

    public DbSet<pos_autorizacionsri> pos_autorizacionsri { get; set; }

    public DbSet<ViewPagoDetalleUsuario> ViewPagoDetalleUsuarios { get; set; }

    public DbSet<ViewFacturaPagoUsuario> ViewFacturaPagoUsuarios { get; set; }

    public DbSet<auth_user> auth_user { get; set; }

    public DbSet<auth_group> auth_group { get; set; }

    public DbSet<auth_user_groups> auth_user_groups { get; set; }

    public DbSet<core_promocionticket_items> core_promocionticket_items { get; set; }

    public DbSet<core_facturadetalle_carnicero> core_facturadetalle_carnicero { get; set; }

    public DbSet<View_CarnicerosAX> View_CarnicerosAX { get; set; }

    public DbSet<View_AlmacenProductoPeso> View_AlmacenProductoPeso { get; set; }

    public DbSet<ax_viewCorteCredito> ax_viewCorteCredito { get; set; }

    public DbSet<core_factura_view> core_factura_view { get; set; }

    public DbSet<core_facturadetalle_view> core_facturadetalle_view { get; set; }

    public DbSet<core_facturapago_view> core_facturapago_view { get; set; }

    public DbSet<ViewDetalleAcumulado> ViewDetalleAcumuladoes { get; set; }

    public DbSet<ViewEstablecimientoTotal> ViewEstablecimientoTotals { get; set; }

    public DbSet<ViewFacturasPagoCredito> ViewFacturasPagoCreditoes { get; set; }

    public DbSet<ViewPagosCredito> ViewPagosCreditoes { get; set; }

    public DbSet<ViewTicketsCarnicero> ViewTicketsCarniceros { get; set; }

    public DbSet<vw_PreciosPOS> vw_PreciosPOS { get; set; }

    public DbSet<auth_group_permissions> auth_group_permissions { get; set; }

    public DbSet<auth_permission> auth_permission { get; set; }

    public DbSet<auth_user_user_permissions> auth_user_user_permissions { get; set; }

    public DbSet<core_descuentotipo> core_descuentotipo { get; set; }

    public DbSet<core_empresacredito> core_empresacredito { get; set; }

    public DbSet<core_empresacreditocorte> core_empresacreditocorte { get; set; }

    public DbSet<core_empresacreditopago> core_empresacreditopago { get; set; }

    public DbSet<core_giftcard_migracion> core_giftcard_migracion { get; set; }

    public DbSet<core_poscustomergroup> core_poscustomergroup { get; set; }

    public DbSet<django_admin_log> django_admin_log { get; set; }

    public DbSet<django_content_type> django_content_type { get; set; }

    public DbSet<django_session> django_session { get; set; }

    public DbSet<django_site> django_site { get; set; }

    public DbSet<pos_customer_group> pos_customer_group { get; set; }

    public DbSet<sitetree_tree> sitetree_tree { get; set; }

    public DbSet<sitetree_treeitem> sitetree_treeitem { get; set; }

    public DbSet<sitetree_treeitem_access_permissions> sitetree_treeitem_access_permissions { get; set; }

    public DbSet<mt_FacturasRezagadas> mt_FacturasRezagadas { get; set; }

    public DbSet<ProduccionAx> ProduccionAxes { get; set; }

    public DbSet<tblNavidadLMAT> tblNavidadLMATs { get; set; }

    public DbSet<VW_ITEMBARCODEQTY> VW_ITEMBARCODEQTY { get; set; }

    public DbSet<core_descuento> core_descuento { get; set; }

    public DbSet<vw_CreditoLocalesCabecera> vw_CreditoLocalesCabecera { get; set; }

    public DbSet<vw_CreditoLocalesMensajes> vw_CreditoLocalesMensajes { get; set; }

    public DbSet<vw_CreditoLocalesPagos> vw_CreditoLocalesPagos { get; set; }

    public DbSet<VW_CombosCaja> VW_CombosCaja { get; set; }

    public DbSet<TblAuthorizeDeleteProduct> TblAuthorizeDeleteProducts { get; set; }

    public DbSet<TblDeletedProduct> TblDeletedProducts { get; set; }

    public DbSet<VW_SEARCHPRODUCT> VW_SEARCHPRODUCT { get; set; }

    public DbSet<TblFeriado> TblFeriados { get; set; }

    public DbSet<VW_BLOCK_PRODUCTS> VW_BLOCK_PRODUCTS { get; set; }

    public DbSet<TblInvoiceCounter> TblInvoiceCounters { get; set; }

    public DbSet<TblInvoiceRandom> TblInvoiceRandoms { get; set; }

    public DbSet<TblInvoiceWinner> TblInvoiceWinners { get; set; }

    public DbSet<TblDiscountCard> TblDiscountCards { get; set; }

    public DbSet<TblDiscountCardTran> TblDiscountCardTrans { get; set; }

    public DbSet<ax_viewConsumoCreditoCliente> ax_viewConsumoCreditoCliente { get; set; }

    public DbSet<VW_PromoChoose> VW_PromoChoose { get; set; }

    public DbSet<BG_Apertura> BG_Apertura { get; set; }

    public DbSet<BG_Lst_POS_no_sub_AX> BG_Lst_POS_no_sub_AX { get; set; }

    public DbSet<core_TarjetaDescuento> core_TarjetaDescuento { get; set; }

    public DbSet<vw_RETIVA> vw_RETIVA { get; set; }

    public DbSet<VW_NC_Motivo> VW_NC_Motivo { get; set; }

    public DbSet<core_TarjetaDescuentoHistorico> core_TarjetaDescuentoHistorico { get; set; }

    public DbSet<cp_ordencabecera> cp_ordencabecera { get; set; }

    public DbSet<cp_ordendetalle> cp_ordendetalle { get; set; }

    public DbSet<POS_VOUCHER> POS_VOUCHER { get; set; }

    public DbSet<core_EnviosArchivosVoucher> core_EnviosArchivosVoucher { get; set; }

    public DbSet<core_tarjetacredito_bin> core_tarjetacredito_bin { get; set; }

    public DbSet<cp_relacion> cp_relacion { get; set; }

    public DbSet<pos_tarjeta_tipopago> pos_tarjeta_tipopago { get; set; }

    public DbSet<pos_tarjeta_transaccion> pos_tarjeta_transaccion { get; set; }

    public DbSet<VW_CP_DETALLE> VW_CP_DETALLE { get; set; }

    public DbSet<pos_itembloq_est> pos_itembloq_est { get; set; }

    public DbSet<pos_itembarra_desc> pos_itembarra_desc { get; set; }

    public DbSet<VW_CATEGORIA> VW_CATEGORIA { get; set; }

    public DbSet<core_promocompragratis> core_promocompragratis { get; set; }

    public DbSet<Tbl_DiferenciaPeso> Tbl_DiferenciaPeso { get; set; }

    public DbSet<LstEncuesta> LstEncuesta { get; set; }

    public DbSet<LstEncuestaEstablecimiento> LstEncuestaEstablecimiento { get; set; }

    public DbSet<LstOpcionesRespuesta> LstOpcionesRespuesta { get; set; }

    public DbSet<LstPregunta> LstPregunta { get; set; }

    public DbSet<TblEncuestaDetalle> TblEncuestaDetalle { get; set; }

    public DbSet<TblEncuestaRealizada> TblEncuestaRealizada { get; set; }

    public DbSet<LstCampania> LstCampania { get; set; }

    public DbSet<LstCampaniaDet> LstCampaniaDet { get; set; }

    public DbSet<LstCampaniaEstablecimientos> LstCampaniaEstablecimientos { get; set; }

    public DbSet<LstProductosCanjear> LstProductosCanjear { get; set; }

    public DbSet<LstProductosCanjearDet> LstProductosCanjearDet { get; set; }

    public DbSet<TblFacturaCanjes> TblFacturaCanjes { get; set; }

    public DbSet<TblFacturasCanjesDet> TblFacturasCanjesDet { get; set; }

    public DbSet<TblPuntos> TblPuntos { get; set; }

    public DbSet<TblPuntosCab> TblPuntosCab { get; set; }

    public DbSet<TblVentaPago> TblVentaPago { get; set; }

    public DbSet<TblVentaTarjeta> TblVentaTarjeta { get; set; }

    public DbSet<LstGrupoCliente> LstGrupoCliente { get; set; }

    public DbSet<TblRegistroParqueo> TblRegistroParqueo { get; set; }

    public DbSet<Core_CargaDocumento> Core_CargaDocumento { get; set; }

    public DbSet<TblCobroCreditoEmp> TblCobroCreditoEmp { get; set; }

    public DbSet<TblCobroCreditoEmpPago> TblCobroCreditoEmpPago { get; set; }

    public DbSet<viewAperturaLogin> viewAperturaLogin { get; set; }

    public DbSet<view_Tbl_Punto_Venta> view_Tbl_Punto_Venta { get; set; }

    public DbSet<core_facturaAPP> core_facturaAPP { get; set; }

    public DbSet<core_facturadetalleAPP> core_facturadetalleAPP { get; set; }

    public DbSet<core_facturapagoAPP> core_facturapagoAPP { get; set; }

    public DbSet<Tbl_PickOrderCab> Tbl_PickOrderCab { get; set; }

    public DbSet<Tbl_PickOrderDet> Tbl_PickOrderDet { get; set; }

    public DbSet<TblPedido> TblPedido { get; set; }

    public DbSet<core_retencion> core_retencion { get; set; }

    public DbSet<TblItemsMaxSales> TblItemsMaxSales { get; set; }

    public DbSet<LstDelivery> LstDelivery { get; set; }

    public DbSet<TblOrdenDelivery> TblOrdenDelivery { get; set; }

    public DbSet<TblOrdenDeliveryDet> TblOrdenDeliveryDet { get; set; }

    public DbSet<core_transaccion_operador> core_transaccion_operador { get; set; }

    public DbSet<Tbl_DineroGiftCardApp> Tbl_DineroGiftCardApp { get; set; }

    public DbSet<TblVacunacion> TblVacunacion { get; set; }

    public DbSet<TblFlete> TblFlete { get; set; }

    public DbSet<core_ClaveAccesoFE> core_ClaveAccesoFE { get; set; }

    public DbSet<core_notacredito> core_notacredito { get; set; }

    public DbSet<core_notacreditodetalle> core_notacreditodetalle { get; set; }

    public DbSet<ViewFacturasUsuarios> ViewFacturasUsuarios { get; set; }

    public DbSet<TblMensaje> TblMensaje { get; set; }

    public DbSet<pos_item> pos_item { get; set; }

    public DbSet<vw_DescuentosCabeceraAX> vw_DescuentosCabeceraAX { get; set; }

    public DbSet<vw_DescuentosDetalleAX> vw_DescuentosDetalleAX { get; set; }

    public DbSet<core_giftcard> core_giftcard { get; set; }


    [EdmFunction("POSEntities", "dss_function_CREDITO_EmpresaFechaCorte")]
    public virtual IQueryable<dss_function_CREDITO_EmpresaFechaCorte_Result> dss_function_CREDITO_EmpresaFechaCorte(string empresa, Nullable<System.DateTime> fecha)
    {

        var empresaParameter = empresa != null ?
            new ObjectParameter("empresa", empresa) :
            new ObjectParameter("empresa", typeof(string));


        var fechaParameter = fecha.HasValue ?
            new ObjectParameter("fecha", fecha) :
            new ObjectParameter("fecha", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<dss_function_CREDITO_EmpresaFechaCorte_Result>("[POSEntities].[dss_function_CREDITO_EmpresaFechaCorte](@empresa, @fecha)", empresaParameter, fechaParameter);
    }


    public virtual int dss_get_saldo_creditodelportal(string tarjeta)
    {

        var tarjetaParameter = tarjeta != null ?
            new ObjectParameter("tarjeta", tarjeta) :
            new ObjectParameter("tarjeta", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dss_get_saldo_creditodelportal", tarjetaParameter);
    }


    public virtual int job_CREDITO_CorteAutomatico()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("job_CREDITO_CorteAutomatico");
    }


    public virtual ObjectResult<Nullable<int>> sp_getPrecioLocalMT(string itemid, string almacen, ObjectParameter precio)
    {

        var itemidParameter = itemid != null ?
            new ObjectParameter("Itemid", itemid) :
            new ObjectParameter("Itemid", typeof(string));


        var almacenParameter = almacen != null ?
            new ObjectParameter("Almacen", almacen) :
            new ObjectParameter("Almacen", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getPrecioLocalMT", itemidParameter, almacenParameter, precio);
    }


    public virtual int sp_getPreciosPos(string almacen, string usuario)
    {

        var almacenParameter = almacen != null ?
            new ObjectParameter("Almacen", almacen) :
            new ObjectParameter("Almacen", typeof(string));


        var usuarioParameter = usuario != null ?
            new ObjectParameter("Usuario", usuario) :
            new ObjectParameter("Usuario", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getPreciosPos", almacenParameter, usuarioParameter);
    }


    public virtual ObjectResult<SP_SECUENCIAS_IG_Result> SP_SECUENCIAS_IG(string oPTION)
    {

        var oPTIONParameter = oPTION != null ?
            new ObjectParameter("OPTION", oPTION) :
            new ObjectParameter("OPTION", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SECUENCIAS_IG_Result>("SP_SECUENCIAS_IG", oPTIONParameter);
    }


    public virtual int sp_setPrecioPos(string aLMACEN, string pRODUCTO, Nullable<decimal> vALOR, Nullable<int> tIPO, Nullable<bool> rANGOFECHA, Nullable<System.DateTime> fECHADESDE, Nullable<System.DateTime> fECHAHASTA, string uSUARIO)
    {

        var aLMACENParameter = aLMACEN != null ?
            new ObjectParameter("ALMACEN", aLMACEN) :
            new ObjectParameter("ALMACEN", typeof(string));


        var pRODUCTOParameter = pRODUCTO != null ?
            new ObjectParameter("PRODUCTO", pRODUCTO) :
            new ObjectParameter("PRODUCTO", typeof(string));


        var vALORParameter = vALOR.HasValue ?
            new ObjectParameter("VALOR", vALOR) :
            new ObjectParameter("VALOR", typeof(decimal));


        var tIPOParameter = tIPO.HasValue ?
            new ObjectParameter("TIPO", tIPO) :
            new ObjectParameter("TIPO", typeof(int));


        var rANGOFECHAParameter = rANGOFECHA.HasValue ?
            new ObjectParameter("RANGOFECHA", rANGOFECHA) :
            new ObjectParameter("RANGOFECHA", typeof(bool));


        var fECHADESDEParameter = fECHADESDE.HasValue ?
            new ObjectParameter("FECHADESDE", fECHADESDE) :
            new ObjectParameter("FECHADESDE", typeof(System.DateTime));


        var fECHAHASTAParameter = fECHAHASTA.HasValue ?
            new ObjectParameter("FECHAHASTA", fECHAHASTA) :
            new ObjectParameter("FECHAHASTA", typeof(System.DateTime));


        var uSUARIOParameter = uSUARIO != null ?
            new ObjectParameter("USUARIO", uSUARIO) :
            new ObjectParameter("USUARIO", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_setPrecioPos", aLMACENParameter, pRODUCTOParameter, vALORParameter, tIPOParameter, rANGOFECHAParameter, fECHADESDEParameter, fECHAHASTAParameter, uSUARIOParameter);
    }


    public virtual int SP_TARJETA_CREDITO(string iD, string nOMBRE)
    {

        var iDParameter = iD != null ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(string));


        var nOMBREParameter = nOMBRE != null ?
            new ObjectParameter("NOMBRE", nOMBRE) :
            new ObjectParameter("NOMBRE", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TARJETA_CREDITO", iDParameter, nOMBREParameter);
    }


    public virtual int spCargarFacturasAX(string iNVENTLOCATIONID, string uSERID, string dATAAREAID, Nullable<int> cANTIDAD)
    {

        var iNVENTLOCATIONIDParameter = iNVENTLOCATIONID != null ?
            new ObjectParameter("INVENTLOCATIONID", iNVENTLOCATIONID) :
            new ObjectParameter("INVENTLOCATIONID", typeof(string));


        var uSERIDParameter = uSERID != null ?
            new ObjectParameter("USERID", uSERID) :
            new ObjectParameter("USERID", typeof(string));


        var dATAAREAIDParameter = dATAAREAID != null ?
            new ObjectParameter("DATAAREAID", dATAAREAID) :
            new ObjectParameter("DATAAREAID", typeof(string));


        var cANTIDADParameter = cANTIDAD.HasValue ?
            new ObjectParameter("CANTIDAD", cANTIDAD) :
            new ObjectParameter("CANTIDAD", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCargarFacturasAX", iNVENTLOCATIONIDParameter, uSERIDParameter, dATAAREAIDParameter, cANTIDADParameter);
    }


    public virtual int spEnviarMailFacturas()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEnviarMailFacturas");
    }


    public virtual ObjectResult<spGetFacturasPendientes_Result> spGetFacturasPendientes()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFacturasPendientes_Result>("spGetFacturasPendientes");
    }


    public virtual int spGetNavidadLMAT(string aLMACEN, string uSUARIO)
    {

        var aLMACENParameter = aLMACEN != null ?
            new ObjectParameter("ALMACEN", aLMACEN) :
            new ObjectParameter("ALMACEN", typeof(string));


        var uSUARIOParameter = uSUARIO != null ?
            new ObjectParameter("USUARIO", uSUARIO) :
            new ObjectParameter("USUARIO", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetNavidadLMAT", aLMACENParameter, uSUARIOParameter);
    }


    public virtual int spHabilitarFacturasRezagadas()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spHabilitarFacturasRezagadas");
    }


    public virtual int spNotificacionDescuentosFin()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNotificacionDescuentosFin");
    }


    public virtual int spNotificacionDescuentosPrevio()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNotificacionDescuentosPrevio");
    }


    public virtual int spSetNavidadLMAT(string aLMACEN)
    {

        var aLMACENParameter = aLMACEN != null ?
            new ObjectParameter("ALMACEN", aLMACEN) :
            new ObjectParameter("ALMACEN", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSetNavidadLMAT", aLMACENParameter);
    }


    public virtual ObjectResult<SP_GENERABARCODE_Result> SP_GENERABARCODE(Nullable<decimal> vALOR)
    {

        var vALORParameter = vALOR.HasValue ?
            new ObjectParameter("VALOR", vALOR) :
            new ObjectParameter("VALOR", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GENERABARCODE_Result>("SP_GENERABARCODE", vALORParameter);
    }


    public virtual int ActualizarTarjetaDescuentoEspanola(string codigo, Nullable<bool> bono, Nullable<bool> activo, Nullable<int> diasActivo, Nullable<decimal> saldo, Nullable<long> numeroFactura, string codigoCliente)
    {

        var codigoParameter = codigo != null ?
            new ObjectParameter("codigo", codigo) :
            new ObjectParameter("codigo", typeof(string));


        var bonoParameter = bono.HasValue ?
            new ObjectParameter("bono", bono) :
            new ObjectParameter("bono", typeof(bool));


        var activoParameter = activo.HasValue ?
            new ObjectParameter("activo", activo) :
            new ObjectParameter("activo", typeof(bool));


        var diasActivoParameter = diasActivo.HasValue ?
            new ObjectParameter("diasActivo", diasActivo) :
            new ObjectParameter("diasActivo", typeof(int));


        var saldoParameter = saldo.HasValue ?
            new ObjectParameter("saldo", saldo) :
            new ObjectParameter("saldo", typeof(decimal));


        var numeroFacturaParameter = numeroFactura.HasValue ?
            new ObjectParameter("numeroFactura", numeroFactura) :
            new ObjectParameter("numeroFactura", typeof(long));


        var codigoClienteParameter = codigoCliente != null ?
            new ObjectParameter("codigoCliente", codigoCliente) :
            new ObjectParameter("codigoCliente", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarTarjetaDescuentoEspanola", codigoParameter, bonoParameter, activoParameter, diasActivoParameter, saldoParameter, numeroFacturaParameter, codigoClienteParameter);
    }


    public virtual int spTarjetaDescuentoEspanola(string codigo, Nullable<bool> bono, Nullable<bool> activo, Nullable<int> diasActivo, Nullable<decimal> saldo, Nullable<long> numeroFactura, string codigoCliente)
    {

        var codigoParameter = codigo != null ?
            new ObjectParameter("codigo", codigo) :
            new ObjectParameter("codigo", typeof(string));


        var bonoParameter = bono.HasValue ?
            new ObjectParameter("bono", bono) :
            new ObjectParameter("bono", typeof(bool));


        var activoParameter = activo.HasValue ?
            new ObjectParameter("activo", activo) :
            new ObjectParameter("activo", typeof(bool));


        var diasActivoParameter = diasActivo.HasValue ?
            new ObjectParameter("diasActivo", diasActivo) :
            new ObjectParameter("diasActivo", typeof(int));


        var saldoParameter = saldo.HasValue ?
            new ObjectParameter("saldo", saldo) :
            new ObjectParameter("saldo", typeof(decimal));


        var numeroFacturaParameter = numeroFactura.HasValue ?
            new ObjectParameter("numeroFactura", numeroFactura) :
            new ObjectParameter("numeroFactura", typeof(long));


        var codigoClienteParameter = codigoCliente != null ?
            new ObjectParameter("codigoCliente", codigoCliente) :
            new ObjectParameter("codigoCliente", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTarjetaDescuentoEspanola", codigoParameter, bonoParameter, activoParameter, diasActivoParameter, saldoParameter, numeroFacturaParameter, codigoClienteParameter);
    }


    public virtual int sprCallForTransacSQLAcumularPts(string xmlRequest, ObjectParameter respuesta)
    {

        var xmlRequestParameter = xmlRequest != null ?
            new ObjectParameter("xmlRequest", xmlRequest) :
            new ObjectParameter("xmlRequest", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sprCallForTransacSQLAcumularPts", xmlRequestParameter, respuesta);
    }


    public virtual int sprCallForTransacSQLAcumularPtsGen(string xmlRequest, ObjectParameter respuesta)
    {

        var xmlRequestParameter = xmlRequest != null ?
            new ObjectParameter("xmlRequest", xmlRequest) :
            new ObjectParameter("xmlRequest", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sprCallForTransacSQLAcumularPtsGen", xmlRequestParameter, respuesta);
    }


    public virtual int spCuponApp(string tipo, string codigo, Nullable<int> idTblPremio)
    {

        var tipoParameter = tipo != null ?
            new ObjectParameter("tipo", tipo) :
            new ObjectParameter("tipo", typeof(string));


        var codigoParameter = codigo != null ?
            new ObjectParameter("codigo", codigo) :
            new ObjectParameter("codigo", typeof(string));


        var idTblPremioParameter = idTblPremio.HasValue ?
            new ObjectParameter("idTblPremio", idTblPremio) :
            new ObjectParameter("idTblPremio", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCuponApp", tipoParameter, codigoParameter, idTblPremioParameter);
    }

}

}

