//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionAx
    {
        public string productoax { get; set; }
        public int cantidad { get; set; }
        public decimal peso { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string articuloplanificacionax { get; set; }
        public string recepcionconsumo { get; set; }
        public string estado { get; set; }
        public int nivel { get; set; }
        public string diario { get; set; }
        public string ordencompra { get; set; }
        public string almacen { get; set; }
        public string almacen_tran { get; set; }
        public string numero_guia { get; set; }
        public string transportista { get; set; }
        public string placa { get; set; }
        public string num_op { get; set; }
        public string razonsocial_transporte { get; set; }
    }
}
