//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvisionesSql
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Factura { get; set; }
        public string Identifiacion { get; set; }
        public string FormaPago { get; set; }
        public decimal ValorPago { get; set; }
        public int IdTblPuntos { get; set; }
        public int IdTblPuntosCab { get; set; }
        public int Id_Factura { get; set; }
        public decimal Puntos { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public byte Estado { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<byte> Procesado { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> PuntosUsados { get; set; }
        public string Voucher { get; set; }
        public Nullable<decimal> AmountCur { get; set; }
        public Nullable<decimal> SaldoOpen { get; set; }
        public Nullable<decimal> SaldoOpenMST { get; set; }
    }
}
