//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitetree_tree
    {
        public sitetree_tree()
        {
            this.sitetree_treeitem = new HashSet<sitetree_treeitem>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
    
        public virtual ICollection<sitetree_treeitem> sitetree_treeitem { get; set; }
    }
}
