//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitetree_treeitem_access_permissions
    {
        public int id { get; set; }
        public int treeitem_id { get; set; }
        public int permission_id { get; set; }
    
        public virtual auth_permission auth_permission { get; set; }
        public virtual sitetree_treeitem sitetree_treeitem { get; set; }
    }
}
