//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitetree_treeitem
    {
        public sitetree_treeitem()
        {
            this.sitetree_treeitem1 = new HashSet<sitetree_treeitem>();
            this.sitetree_treeitem_access_permissions = new HashSet<sitetree_treeitem_access_permissions>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string hint { get; set; }
        public string url { get; set; }
        public bool urlaspattern { get; set; }
        public int tree_id { get; set; }
        public bool hidden { get; set; }
        public string alias { get; set; }
        public string description { get; set; }
        public bool inmenu { get; set; }
        public bool inbreadcrumbs { get; set; }
        public bool insitetree { get; set; }
        public bool access_loggedin { get; set; }
        public bool access_guest { get; set; }
        public bool access_restricted { get; set; }
        public int access_perm_type { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int sort_order { get; set; }
    
        public virtual sitetree_tree sitetree_tree { get; set; }
        public virtual ICollection<sitetree_treeitem> sitetree_treeitem1 { get; set; }
        public virtual sitetree_treeitem sitetree_treeitem2 { get; set; }
        public virtual ICollection<sitetree_treeitem_access_permissions> sitetree_treeitem_access_permissions { get; set; }
    }
}
