//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MonederoElectronicoProvNoExisten
    {
        public int IdTblPuntos { get; set; }
        public int IdTblPuntosCab { get; set; }
        public int Id_Factura { get; set; }
        public int IdLstCampania { get; set; }
        public decimal FactorPuntos { get; set; }
        public decimal FactorMultiplicador { get; set; }
        public decimal Puntos { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public byte Estado { get; set; }
        public decimal ValorMonetario { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<byte> Procesado { get; set; }
        public System.Guid rowguid { get; set; }
        public string documentnum { get; set; }
    }
}
