//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DiferenciaPeso
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public long numero { get; set; }
        public string Itemid { get; set; }
        public string CodBarra { get; set; }
        public string cliente { get; set; }
        public decimal PesoEtiqueta { get; set; }
        public decimal PesoCaja { get; set; }
        public string usuario { get; set; }
        public string Factura { get; set; }
    }
}
