//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_logcuadrafacutractvo
    {
        public int id_secuencial { get; set; }
        public Nullable<int> numero_factura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string establecimiento { get; set; }
        public string punto_de_emision { get; set; }
        public Nullable<long> numero { get; set; }
        public Nullable<decimal> totalObjetivo { get; set; }
        public Nullable<decimal> totalCorregido { get; set; }
    }
}
