//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PickOrderAuditoriaTmp
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Evento { get; set; }
        public string Usuario { get; set; }
        public int Idfactura { get; set; }
    }
}
