//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DineroGiftCardApp
    {
        public int Id { get; set; }
        public string IdCliente { get; set; }
        public string ProgId { get; set; }
        public string IdGiftCard { get; set; }
        public decimal Saldo { get; set; }
        public byte Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<decimal> Valor { get; set; }
    }
}
