//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAgendaCanje
    {
        public int IdAgenda { get; set; }
        public int IdHorario { get; set; }
        public int IdTblFacturaCanjes { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string ImagenEntrega { get; set; }
        public string UsuarioEntrega { get; set; }
        public Nullable<byte> Estado { get; set; }
    }
}
