
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblAuthorizeDeleteProduct
{

    public string USERID { get; set; }

    public string USERNAME { get; set; }

    public string LOCATIONID { get; set; }

    public bool AUTHORIZE { get; set; }

    public string CODE { get; set; }

    public byte[] Huella { get; set; }

}

}
