
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblCobroCreditoEmp
{

    public TblCobroCreditoEmp()
    {

        this.TblCobroCreditoEmpPago = new HashSet<TblCobroCreditoEmpPago>();

    }


    public int Id { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string Establecimiento { get; set; }

    public string PuntoEmision { get; set; }

    public string Cliente_Ax { get; set; }

    public string Razon_Social { get; set; }

    public decimal Total { get; set; }

    public string Usuario { get; set; }

    public string IdCaja { get; set; }

    public string JournalNum { get; set; }

    public Nullable<byte> Procesado { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public byte TipoTransaccion { get; set; }

    public string CodigoGiftcard { get; set; }



    public virtual ICollection<TblCobroCreditoEmpPago> TblCobroCreditoEmpPago { get; set; }

}

}
