//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCobroCreditoEmpPago
    {
        public int Id { get; set; }
        public int CobroCredEmpId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Tipo_Id { get; set; }
        public decimal Valor { get; set; }
        public string Datos { get; set; }
        public string Voucher { get; set; }
        public string JournalNum { get; set; }
    
        public virtual TblCobroCreditoEmp TblCobroCreditoEmp { get; set; }
    }
}
