//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuponera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCuponera()
        {
            this.TblCuponeraDet = new HashSet<TblCuponeraDet>();
        }
    
        public int IdTblCuponera { get; set; }
        public int IdClienteApp { get; set; }
        public string Cliente { get; set; }
        public int Id_Factura { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Tarjeta { get; set; }
        public string TarjetaValorConsumo { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public byte Estado { get; set; }
        public Nullable<byte> Procesado { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string Establecimiento { get; set; }
        public string PuntoEmision { get; set; }
        public Nullable<long> Numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCuponeraDet> TblCuponeraDet { get; set; }
    }
}
