//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuponeraDet
    {
        public int IdTblCuponeraDet { get; set; }
        public int IdTblCuponera { get; set; }
        public string item_id { get; set; }
        public decimal cantidad { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
    
        public virtual TblCuponera TblCuponera { get; set; }
    }
}
