//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDiscountCard
    {
        public int id { get; set; }
        public Nullable<System.DateTime> emision_date { get; set; }
        public string card { get; set; }
        public string itemid { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<int> times { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
