//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeletedProduct
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> INVOICEDATE { get; set; }
        public string ESTABLISHMENT { get; set; }
        public string EMISIONSERIES { get; set; }
        public Nullable<long> NUMBER { get; set; }
        public string CASHIER { get; set; }
        public string ITEMID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string USERAUTHORIZE { get; set; }
    }
}
