
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblDiscountCardTran
{

    public long id { get; set; }

    public Nullable<System.DateTime> trans_date { get; set; }

    public string card { get; set; }

    public string invoiceid { get; set; }

}

}
