//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblETLLog
    {
        public int Id { get; set; }
        public string Mensaje_Error { get; set; }
        public string Nombre_Srv { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
