//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEncuestaRealizada
    {
        public TblEncuestaRealizada()
        {
            this.TblEncuestaDetalle = new HashSet<TblEncuestaDetalle>();
        }
    
        public int IdEncuestaRealizada { get; set; }
        public short IdEncuesta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdFactura { get; set; }
    
        public virtual LstEncuesta LstEncuesta { get; set; }
        public virtual ICollection<TblEncuestaDetalle> TblEncuestaDetalle { get; set; }
    }
}
