
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblFacturasCanjesDet
{

    public int IdTblFacturasCanjesDet { get; set; }

    public int IdTblFacturaCanjes { get; set; }

    public int Item_Id { get; set; }

    public string Usuario { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public decimal Cantidad { get; set; }

    public decimal Puntos { get; set; }

    public decimal ValorMoneda { get; set; }

    public decimal CostoPuntos { get; set; }

    public decimal CostoMoneda { get; set; }



    public virtual TblFacturaCanjes TblFacturaCanjes { get; set; }

}

}
