
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblFacturaCanjes
{

    public TblFacturaCanjes()
    {

        this.TblFacturasCanjesDet = new HashSet<TblFacturasCanjesDet>();

    }


    public int IdTblFacturaCanjes { get; set; }

    public System.DateTime Fecha { get; set; }

    public decimal ValorConversion { get; set; }

    public string AccountNum { get; set; }

    public decimal TotalCanje { get; set; }

    public int TotalPuntos { get; set; }

    public byte Estado { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModifica { get; set; }

    public string UsuarioModifica { get; set; }



    public virtual ICollection<TblFacturasCanjesDet> TblFacturasCanjesDet { get; set; }

}

}
