//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFragmentacionTablas
    {
        public string Schema { get; set; }
        public string Table { get; set; }
        public string Index { get; set; }
        public Nullable<double> avg_fragmentation_in_percent { get; set; }
        public Nullable<long> page_count { get; set; }
        public string SQLReindex { get; set; }
    }
}
