//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFlete1
    {
        public int Id { get; set; }
        public string Establecimiento { get; set; }
        public string Punto_emision { get; set; }
        public int OrdenId { get; set; }
        public string IdMotorizado { get; set; }
        public string NombreMotorizado { get; set; }
        public string IdCaja { get; set; }
        public string IpProceso { get; set; }
        public decimal Total { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte Estado { get; set; }
        public System.DateTime FechaOrdenCompletado { get; set; }
    }
}
