//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFacturaOrderId
    {
        public long RecNo { get; set; }
        public int FacturaId { get; set; }
        public string OrderId { get; set; }
        public System.DateTime CrtDateTime { get; set; }
    }
}
