//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGenGiftcardBono
    {
        public int Id { get; set; }
        public string Identifiacion { get; set; }
        public string codigoGiftcard { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
