//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHistorialEstadoOrders1
    {
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public byte Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Usuario { get; set; }
    }
}
