
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblInvoiceCounter
{

    public long id { get; set; }

    public string establishment { get; set; }

    public Nullable<int> counter { get; set; }

    public Nullable<bool> status { get; set; }

}

}
