//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceWinner
    {
        public long id { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public string establishment { get; set; }
        public string emisionseries { get; set; }
        public string invoiceid { get; set; }
        public string customer { get; set; }
        public string resource { get; set; }
        public Nullable<decimal> value { get; set; }
    }
}
