
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblItemsMaxSales
{

    public string ItemId { get; set; }

    public string Articulo { get; set; }

    public string Categoria { get; set; }

    public string Establecimiento { get; set; }

    public int Orden { get; set; }

}

}
