//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMensaje
    {
        public int id { get; set; }
        public string opcion { get; set; }
        public string descripcion { get; set; }
        public string titulo_mensaje { get; set; }
        public string tipo_mensaje { get; set; }
        public int tiempo_espera { get; set; }
        public Nullable<bool> activo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    }
}
