
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblNavidadLMAT
{

    public int factura_id { get; set; }

    public string Almacen { get; set; }

    public bool Seleccionado { get; set; }

    public bool Procesado { get; set; }

    public string Usuario { get; set; }

}

}
