
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblOrdenDeliveryDet
{

    public int Id { get; set; }

    public Nullable<int> IdOrdenGlovo { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public Nullable<decimal> Cantidad { get; set; }

    public Nullable<decimal> price { get; set; }

    public string ItemId { get; set; }

}

}
