//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrdenDelivery
    {
        public int Id { get; set; }
        public int IdDelivery { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Establecimiento { get; set; }
        public string OrderId { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string PaymentMethod { get; set; }
        public string OrderCode { get; set; }
        public string PickUpCode { get; set; }
        public string CourierName { get; set; }
        public string CourierNumber { get; set; }
        public Nullable<byte> Estado { get; set; }
    
        public virtual LstDelivery LstDelivery { get; set; }
    }
}
