//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPremio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPremio()
        {
            this.TblPremioDet = new HashSet<TblPremioDet>();
        }
    
        public int IdTblPremio { get; set; }
        public int IdClienteApp { get; set; }
        public string Cliente { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> CantAplicar { get; set; }
        public Nullable<byte> Procesado { get; set; }
        public Nullable<byte> ProcesadoPos { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPremioDet> TblPremioDet { get; set; }
    }
}
