//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPedido
    {
        public int Id { get; set; }
        public string Pedido { get; set; }
        public int Factura_Id { get; set; }
        public byte Tipo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int Estado { get; set; }
    
        public virtual core_factura core_factura { get; set; }
    }
}
