//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPuntosCab
    {
        public TblPuntosCab()
        {
            this.TblPuntos = new HashSet<TblPuntos>();
        }
    
        public int IdTblPuntosCab { get; set; }
        public string AccountNum { get; set; }
        public decimal Puntos { get; set; }
        public decimal Saldo { get; set; }
        public byte Estado { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<TblPuntos> TblPuntos { get; set; }
    }
}
