
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblPuntos
{

    public int IdTblPuntos { get; set; }

    public int IdTblPuntosCab { get; set; }

    public int Id_Factura { get; set; }

    public int IdLstCampania { get; set; }

    public decimal FactorPuntos { get; set; }

    public decimal Puntos { get; set; }

    public decimal Saldo { get; set; }

    public System.DateTime FechaEmision { get; set; }

    public Nullable<System.DateTime> FechaExpiracion { get; set; }

    public byte Estado { get; set; }

    public decimal ValorMonetario { get; set; }

    public string UsuarioModifica { get; set; }

    public Nullable<System.DateTime> FechaModifica { get; set; }

    public decimal FactorMultiplicador { get; set; }

    public Nullable<byte> Procesado { get; set; }

    public string establecimiento { get; set; }

    public string punto_emision { get; set; }

    public Nullable<long> numero { get; set; }



    public virtual LstCampania LstCampania { get; set; }

    public virtual TblPuntosCab TblPuntosCab { get; set; }

}

}
