//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPriceNewProduct
    {
        public int Id { get; set; }
        public string Almacen { get; set; }
        public string ItemId { get; set; }
        public decimal PrecioNuevo { get; set; }
        public Nullable<decimal> PrecioAnterior { get; set; }
        public Nullable<decimal> DescuentoNuevo { get; set; }
        public Nullable<decimal> DescuentoAnterior { get; set; }
        public byte Estado { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
