//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPremioDet
    {
        public int IdTblPremioDet { get; set; }
        public int IdTblPremio { get; set; }
        public string item_id { get; set; }
    
        public virtual TblPremio TblPremio { get; set; }
    }
}
