
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblVacunacion
{

    public string CEDULA { get; set; }

    public string NOM_PADRON { get; set; }

    public string NOM_PROVINCIA { get; set; }

    public string NOM_CANTON { get; set; }

    public string NOM_PARROQUIA { get; set; }

    public string NOM_RECINTO { get; set; }

    public string DIR_RECINTO { get; set; }

    public string DOSIS_1 { get; set; }

    public string DOSIS_2 { get; set; }

}

}
