//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vieFacturasCreditoEmpresas
    {
        public string descripcion { get; set; }
        public string tarjeta { get; set; }
        public decimal valor { get; set; }
        public int empresa_id { get; set; }
        public string codigo { get; set; }
        public string identificacion { get; set; }
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public long numero { get; set; }
        public string documento { get; set; }
        public string cliente_ax { get; set; }
        public string cliente { get; set; }
        public string razon_social { get; set; }
        public string direccion { get; set; }
        public decimal base0 { get; set; }
        public decimal base12 { get; set; }
        public decimal subtotal { get; set; }
        public decimal descuento { get; set; }
        public decimal descuento2 { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public string autorizacion { get; set; }
        public string ip { get; set; }
        public string usuario { get; set; }
        public string orderID { get; set; }
        public bool loadinvoice { get; set; }
        public bool loadpaym { get; set; }
        public string msgError { get; set; }
        public string paymID { get; set; }
        public decimal descuentoPorc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NumFact { get; set; }
        public string NomEstablecimiento { get; set; }
        public string Empresa { get; set; }
    }
}
