//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vieInvCustomerRevision
    {
        public string Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public Nullable<decimal> PuntosMonedero { get; set; }
        public Nullable<System.DateTime> FechaUltimCompra { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public Nullable<decimal> SaldoGifCard { get; set; }
        public Nullable<decimal> SaldoTarEmp { get; set; }
        public int Descuento { get; set; }
        public int isTarEmp { get; set; }
        public string EsEmpleado { get; set; }
    }
}
