//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vieRespuestaEncuesta
    {
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public byte tipoPregunta { get; set; }
        public string identificacion { get; set; }
        public string nombreCliente { get; set; }
        public string custGroup { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estNombre { get; set; }
        public string establecimiento { get; set; }
        public string puntoEmision { get; set; }
        public long numero { get; set; }
        public decimal totalFactura { get; set; }
    }
}
