
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ViewEstablecimientoTotal
{

    public string establecimiento { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public Nullable<decimal> subtotal { get; set; }

    public Nullable<decimal> descuento { get; set; }

    public Nullable<decimal> descuento2 { get; set; }

    public Nullable<decimal> iva { get; set; }

    public Nullable<decimal> total { get; set; }

}

}
