//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCargaFacturasDet
    {
        public int IdSales { get; set; }
        public string InventLocationId { get; set; }
        public int LineNum { get; set; }
        public string ItemId { get; set; }
        public int ItemType { get; set; }
        public string Description { get; set; }
        public string SalesUnit { get; set; }
        public string Dimension { get; set; }
        public decimal SalesQty { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal SalesCost { get; set; }
        public Nullable<decimal> LineAmount { get; set; }
        public Nullable<decimal> LineDisc { get; set; }
        public int Tax { get; set; }
        public int Stock { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int RecId { get; set; }
    }
}
