//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCargaFacturasPagos
    {
        public int IdSales { get; set; }
        public int IdPaym { get; set; }
        public Nullable<System.DateTime> PaymDate { get; set; }
        public string PayMode { get; set; }
        public decimal Amount { get; set; }
        public string PaySpec { get; set; }
        public string PaymReference { get; set; }
        public string PaymentNotes { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<long> RecId { get; set; }
        public string ID_Caja { get; set; }
        public string cliente { get; set; }
        public string tipo_id { get; set; }
    }
}
