//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAperturaLogin
    {
        public int id { get; set; }
        public string username { get; set; }
        public bool is_staff { get; set; }
        public byte[] huella { get; set; }
        public byte[] imagen { get; set; }
        public bool is_active { get; set; }
        public string punto_venta { get; set; }
        public string turno { get; set; }
        public string inventlocation { get; set; }
        public string ip { get; set; }
        public bool is_superuser { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public string id_caja { get; set; }
    }
}
