//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCargaFacturasCab
    {
        public int IdSales { get; set; }
        public Nullable<System.DateTime> DateInvoice { get; set; }
        public string TypeDoc { get; set; }
        public string InvoiceAccount { get; set; }
        public string SalesResponsible { get; set; }
        public string InventLocationId { get; set; }
        public string PosInvoiceName { get; set; }
        public string InvoiceName { get; set; }
        public int LoadInvoice { get; set; }
        public decimal Discount1 { get; set; }
        public decimal Discount2 { get; set; }
        public decimal Total { get; set; }
        public int Stock { get; set; }
        public int LoadLines { get; set; }
        public int Facturado { get; set; }
        public int Pagado { get; set; }
        public string Mensaje { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string DataAreaId { get; set; }
        public int RecId { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Address { get; set; }
        public string ID_Caja { get; set; }
        public int DiscPercent { get; set; }
        public string SalesOriginId { get; set; }
    }
}
