//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_cuadre_Caja
    {
        public string fecha_creacion { get; set; }
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public string documento { get; set; }
        public string cliente_ax { get; set; }
        public string razon_social { get; set; }
        public decimal total { get; set; }
        public string usuario { get; set; }
        public string datos { get; set; }
        public string voucher { get; set; }
        public string almacen { get; set; }
        public string nombre { get; set; }
        public System.DateTime Expr2 { get; set; }
        public decimal valor { get; set; }
    }
}
