
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class view_Tbl_Punto_Venta
{

    public string DATAAREAID { get; set; }

    public int RECVERSION { get; set; }

    public long RECID { get; set; }

    public string PUNTO_VENTA { get; set; }

    public string INVENTLOCATION { get; set; }

    public string ESTABLECIMIENTO { get; set; }

    public string PUNTO_EMISION { get; set; }

    public string M_ADDRESS { get; set; }

    public int RESERVADO { get; set; }

    public string IP { get; set; }

}

}
