//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFacturasUsuarios
    {
        public string establecimiento { get; set; }
        public string punto_emision { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string usuario { get; set; }
        public Nullable<int> numerofactura { get; set; }
    }
}
