//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTicketsCarniceros
    {
        public System.DateTime FECHA_CREACION { get; set; }
        public string ITEMID { get; set; }
        public string ITEM_NOMBRE { get; set; }
        public string CODIGOCARNICERO { get; set; }
        public string NOMBRECARNICERO { get; set; }
        public string IDALMACEN { get; set; }
        public string ALMACEN { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal UNIDADES { get; set; }
        public decimal TOTAL { get; set; }
    }
}
