//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPagosCredito
    {
        public System.DateTime fecha { get; set; }
        public string tarjeta { get; set; }
        public string cliente { get; set; }
        public string ruc { get; set; }
        public decimal valor { get; set; }
        public string descripcion { get; set; }
        public string NAME { get; set; }
        public string razon_social { get; set; }
    }
}
