
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ViewTicketsCarnicero
{

    public System.DateTime FECHA_CREACION { get; set; }

    public string ITEMID { get; set; }

    public string ITEM_NOMBRE { get; set; }

    public string CODIGOCARNICERO { get; set; }

    public string NOMBRECARNICERO { get; set; }

    public string IDALMACEN { get; set; }

    public string ALMACEN { get; set; }

    public decimal CANTIDAD { get; set; }

    public decimal UNIDADES { get; set; }

    public decimal TOTAL { get; set; }

}

}
