//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewSecuenciaFactura
    {
        public string establecimiento_id { get; set; }
        public string nombre { get; set; }
        public string punto_emision { get; set; }
        public string IpPtoEmision { get; set; }
        public Nullable<int> secuencia { get; set; }
        public Nullable<int> secuenciaFactura { get; set; }
        public string CodigoCoreDocumento { get; set; }
        public bool EstadoPtoEmision { get; set; }
    }
}
