//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFacturasPagoCredito
    {
        public string Factura { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public decimal valor { get; set; }
        public string cliente_ax { get; set; }
        public string razon_social { get; set; }
        public string tarjeta { get; set; }
        public string empresa { get; set; }
    }
}
