
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VW_BLOCK_PRODUCTS
{

    public string PRODUCT { get; set; }

    public string BARCODE { get; set; }

    public decimal QTY { get; set; }

    public string DESCRIPTION { get; set; }

    public string SETPRODUCT { get; set; }

    public string CATEGORY { get; set; }

    public string VARIETY { get; set; }

    public string GROUPS { get; set; }

    public string SUBGROUP { get; set; }

    public string VENDORID { get; set; }

}

}
