//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CreditoLocalesCabecera
    {
        public string CLIENTE { get; set; }
        public string CLIENTENOMBRE { get; set; }
        public System.DateTime FECHACONTRATO { get; set; }
        public System.DateTime FECHAENTREGA { get; set; }
        public System.DateTime FECHAVENCIMIENTO { get; set; }
        public string LOCALENTREGA { get; set; }
        public string NOMBRELOCAL { get; set; }
        public int ESTADO { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ABONADO { get; set; }
        public int ENTREGADO { get; set; }
        public string LOCALCONTRATO { get; set; }
        public int ANULADO { get; set; }
    }
}
