//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CombosCaja
    {
        public string ITEMRELATION { get; set; }
        public string ITEMNAME { get; set; }
        public string SUPPITEMID { get; set; }
        public string SUPPITEMNAME { get; set; }
        public string UNITID { get; set; }
        public System.DateTime FROMDATE { get; set; }
        public System.DateTime TODATE { get; set; }
        public decimal MULTIPLEQTY { get; set; }
        public decimal SUPPITEMQTY { get; set; }
        public int SUPPITEMFREE { get; set; }
        public int SUPPITEMOPTIONAL { get; set; }
        public string ITEMRELATIONCODE { get; set; }
        public string SUPPITEMCODE { get; set; }
        public string ACCOUNTRELATION { get; set; }
    }
}
