//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CobrosPinpad
    {
        public string fechaconsumo { get; set; }
        public string establecimiento { get; set; }
        public string nombre { get; set; }
        public string valorconsumo { get; set; }
        public string grupotar { get; set; }
        public int autorizador { get; set; }
    }
}
