
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_CreditoLocalesMensajes
{

    public int TIPOMENSAJE { get; set; }

    public string MENSAJE { get; set; }

    public string DATAAREAID { get; set; }

    public int RECVERSION { get; set; }

    public long RECID { get; set; }

}

}
