//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ConsultaPaviPlan
    {
        public string CLIENTE { get; set; }
        public string CLIENTENOMBRE { get; set; }
        public decimal ABONADO { get; set; }
        public int ENTREGADO { get; set; }
        public System.DateTime FECHACONTRATO { get; set; }
        public System.DateTime FECHAENTREGA { get; set; }
        public System.DateTime FECHAVENCIMIENTO { get; set; }
        public string LOCALENTREGA { get; set; }
        public int ESTADO { get; set; }
        public int IMPRESO { get; set; }
        public int REIMPRESO { get; set; }
        public System.DateTime FECHAIMPRESION { get; set; }
        public decimal TOTAL { get; set; }
        public string LOCALCONTRATO { get; set; }
        public int DESPACHADO { get; set; }
        public int ANULADO { get; set; }
        public string FACTURA { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long RECID { get; set; }
        public string SUPERVISOR { get; set; }
        public System.DateTime FECHADESPACHO { get; set; }
        public string DESPACHOUSUARIO { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
    }
}
