//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CreditoLocalesPagos
    {
        public System.DateTime FECHA { get; set; }
        public string CLIENTE { get; set; }
        public decimal MONTO { get; set; }
        public decimal SALDO { get; set; }
        public string LOCAL { get; set; }
        public string CAJERO { get; set; }
        public string ESTABLECIMIENTO { get; set; }
        public string NOMBRELOCAL { get; set; }
        public int FORMAPAGO { get; set; }
        public string DETALLE { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long RECID { get; set; }
    }
}
