
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_DescuentosCabeceraAX
{

    public string ALMACEN { get; set; }

    public int TIPODESCUENTO { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<System.DateTime> FECHADESDE { get; set; }

    public Nullable<System.DateTime> FECHAHASTA { get; set; }

    public int FECHADESDETZID { get; set; }

    public int FECHAHASTATZID { get; set; }

    public int ESTADO { get; set; }

    public int LUNES { get; set; }

    public int MARTES { get; set; }

    public int MIERCOLES { get; set; }

    public int JUEVES { get; set; }

    public int VIERNES { get; set; }

    public int SABADO { get; set; }

    public int DOMINGO { get; set; }

    public string DATAAREAID { get; set; }

    public int RECVERSION { get; set; }

    public long RECID { get; set; }

}

}
