//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DescuentosDetalleAX
    {
        public long REFRECID { get; set; }
        public string ITEMID { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal DESCUENTO { get; set; }
        public int TIENEDESCUENTO { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long RECID { get; set; }
        public string ITEMBARCODE { get; set; }
        public int APP { get; set; }
        public int SHOWAPP { get; set; }
        public int POS { get; set; }
    }
}
