//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DETALLECONSUMOEMPLEADOS
    {
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_ZERO { get; set; }
        public string EMP { get; set; }
        public string NOMEMP { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal DESC_EMPLEADO { get; set; }
        public decimal IVA { get; set; }
        public decimal TOTAL_FACTURA { get; set; }
        public decimal TOTAL_TARJETA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
