//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ITEMBARCODEQTY
    {
        public long RECID { get; set; }
        public string ITEMBARCODE { get; set; }
        public string ITEMID { get; set; }
        public string INVENTDIMID { get; set; }
        public decimal QTY { get; set; }
        public string BARCODESETUPID { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public int DEL_MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public string DATAAREAID { get; set; }
    }
}
