
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VW_PromoChoose
{

    public string ITEMID { get; set; }

    public string BARCODE { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<decimal> QTY { get; set; }

    public string P1 { get; set; }

    public string P2 { get; set; }

    public string P3 { get; set; }

    public Nullable<decimal> PRECIO_COMBO { get; set; }

    public Nullable<decimal> PVP { get; set; }

    public decimal IVA { get; set; }

    public Nullable<bool> ESTADO { get; set; }

}

}
