
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_PreciosPOS
{

    public string ALMACEN { get; set; }

    public string ITEMID { get; set; }

    public string ITEMNAME { get; set; }

    public Nullable<decimal> PLM { get; set; }

    public decimal DSCE { get; set; }

    public decimal DSCP { get; set; }

    public decimal DSCEP { get; set; }

    public Nullable<decimal> TAXVALUE { get; set; }

    public Nullable<decimal> PVP { get; set; }

    public string UNITID { get; set; }

    public string ITEMBARCODE { get; set; }

}

}
