//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_POS_ELIMINACIONARTICULOS
    {
        public Nullable<System.DateTime> FECHA { get; set; }
        public string LOCAL { get; set; }
        public string LOCALNOMBRE { get; set; }
        public string FACTURA { get; set; }
        public string CAJEROID { get; set; }
        public string CAJERONOMBRE { get; set; }
        public string ITEMID { get; set; }
        public string ITEMNAME { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
