
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VW_SEARCHPRODUCT
{

    public string ARTICULO { get; set; }

    public string BARRAS { get; set; }

    public string CATEGORIA { get; set; }

    public string ESTABLECIMIENTO { get; set; }

    public int ORDEN { get; set; }

}

}
