//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SearchMaxSalesLocal
    {
        public string item_id { get; set; }
        public string Articulo { get; set; }
        public string BARRAS { get; set; }
        public string categoria { get; set; }
        public string establecimiento { get; set; }
        public Nullable<long> maxitems { get; set; }
    }
}
