//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VENTA_HORARIA
    {
        public System.DateTime INVOICEDATE { get; set; }
        public string INVOICEID { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public string ITEMID { get; set; }
        public decimal QTY { get; set; }
        public decimal LINEAMOUNT { get; set; }
    }
}
