//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFacturasPagos
    {
        public string Almacen { get; set; }
        public string Descripcion { get; set; }
        public string Factura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string Cliente { get; set; }
        public string RazonSocial { get; set; }
        public string FormaPago { get; set; }
        public decimal Valor { get; set; }
    }
}
