//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGifcardClientesDet
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Factura { get; set; }
        public decimal Valor { get; set; }
        public string Tipo { get; set; }
        public string Cliente { get; set; }
    }
}
