//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPuntosGeneradoNew
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Establecimiento { get; set; }
        public int IdFactura { get; set; }
        public string Factura { get; set; }
        public string Identifiacion { get; set; }
        public string Nombre { get; set; }
        public decimal base0 { get; set; }
        public decimal base12 { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public string FormaPago { get; set; }
        public decimal ValorPago { get; set; }
        public int IdTblPuntos { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
