//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVentasAppPos
    {
        public System.DateTime Fecha { get; set; }
        public string Almacen { get; set; }
        public string Descripcion { get; set; }
        public decimal APP_Order { get; set; }
        public string APP_Cliente { get; set; }
        public string APP_Nombres { get; set; }
        public string APP_FormaPago { get; set; }
        public Nullable<decimal> APP_Valor { get; set; }
        public string APP_TipoCompra { get; set; }
        public decimal POS_Valor { get; set; }
        public string POS_FormaPago { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public string ExisteDif { get; set; }
        public string Subida { get; set; }
        public string Datos { get; set; }
        public Nullable<int> Pedido_fact { get; set; }
        public Nullable<int> Dbo_factura { get; set; }
        public Nullable<int> Dbo_factura2 { get; set; }
    }
}
