//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudRecaudaciones
    {
        public int Id { get; set; }
        public Nullable<int> IdRecaudacionTran { get; set; }
        public short TipoTransaccion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Trama { get; set; }
        public string Equipo { get; set; }
    
        public virtual CatalogosRecaudoDet LstCatalogosRecaudoDet { get; set; }
    }
}
