//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosRecaudo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosRecaudo()
        {
            this.LstCatalogosRecaudoDet = new HashSet<CatalogosRecaudoDet>();
        }
    
        public short IdCatalogosRecaudo { get; set; }
        public string IdTabla { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosRecaudoDet> LstCatalogosRecaudoDet { get; set; }
    }
}
