//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CorrBanEntities : DbContext
    {
        public CorrBanEntities()
            : base("name=CorrBanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatalogosRecaudo> CatalogosRecaudo { get; set; }
        public virtual DbSet<CatalogosRecaudoDet> CatalogosRecaudoDet { get; set; }
        public virtual DbSet<ReglasRecaudos> ReglasRecaudos { get; set; }
        public virtual DbSet<InstRecaudos> InstRecaudos { get; set; }
        public virtual DbSet<SoapCorrBan> SoapCorrBan { get; set; }
        public virtual DbSet<SoapCorrBanDet> SoapCorrBanDet { get; set; }
        public virtual DbSet<Recaudaciones> Recaudaciones { get; set; }
        public virtual DbSet<AudRecaudaciones> AudRecaudaciones { get; set; }
        public virtual DbSet<VieReqsWF> VieReqsWF { get; set; }
    
        public virtual int spGetDetCatalogId(string nameCab, string nameDet)
        {
            var nameCabParameter = nameCab != null ?
                new ObjectParameter("nameCab", nameCab) :
                new ObjectParameter("nameCab", typeof(string));
    
            var nameDetParameter = nameDet != null ?
                new ObjectParameter("nameDet", nameDet) :
                new ObjectParameter("nameDet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetDetCatalogId", nameCabParameter, nameDetParameter);
        }
    
        public virtual int spProcesaSolicitud(string xml, ObjectParameter respuesta)
        {
            var xmlParameter = xml != null ?
                new ObjectParameter("Xml", xml) :
                new ObjectParameter("Xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spProcesaSolicitud", xmlParameter, respuesta);
        }
    
        public virtual ObjectResult<string> spPingRequest(string xml)
        {
            var xmlParameter = xml != null ?
                new ObjectParameter("Xml", xml) :
                new ObjectParameter("Xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spPingRequest", xmlParameter);
        }
    
        public virtual int spProcesaRecaudacion(string xml, ObjectParameter respuesta)
        {
            var xmlParameter = xml != null ?
                new ObjectParameter("Xml", xml) :
                new ObjectParameter("Xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spProcesaRecaudacion", xmlParameter, respuesta);
        }
    }
}
