//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstRecaudos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstRecaudos()
        {
            this.LstReglasRecaudos = new HashSet<ReglasRecaudos>();
            this.TblRecaudaciones1 = new HashSet<Recaudaciones>();
        }
    
        public short IdIRecaudos { get; set; }
        public short IdTipoCorrBan { get; set; }
        public string CodigoEmpresa { get; set; }
        public string NombreEntidad { get; set; }
        public string SubTipo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string UsuarioCrea { get; set; }
        public string UsuarioModifica { get; set; }
        public decimal Min { get; set; }
        public decimal Max { get; set; }
        public bool AplicaAbono { get; set; }
        public decimal Costo { get; set; }
        public string Logo { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReglasRecaudos> LstReglasRecaudos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recaudaciones> TblRecaudaciones1 { get; set; }
    }
}
