//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recaudaciones
    {
        public int Id { get; set; }
        public int PkgNo { get; set; }
        public string CodigoCliente { get; set; }
        public string Cuenta { get; set; }
        public int Secuencial { get; set; }
        public System.DateTime FechaPago { get; set; }
        public short IdIRecaudos { get; set; }
        public decimal ValorRecaudado { get; set; }
        public int SecuencialSara { get; set; }
        public string Estado { get; set; }
        public string Terminal { get; set; }
        public string Operador { get; set; }
        public string Canal { get; set; }
        public string Establecimiento { get; set; }
        public string PuntoEmision { get; set; }
        public string SecuenciaFactura { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short EstadoProceso { get; set; }
        public string UsuarioModifica { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string TipoTransCorresponsal { get; set; }
        public string ActivaId { get; set; }
        public string IdCajaApertura { get; set; }
    
        public virtual InstRecaudos LstIRecaudos { get; set; }
    }
}
