//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglasRecaudos
    {
        public short Id { get; set; }
        public short IdIRecaudos { get; set; }
        public string IdTipoServicio { get; set; }
        public string TipoServicio { get; set; }
        public string CampoObliga { get; set; }
        public string CampoOpcional { get; set; }
        public bool Estado { get; set; }
    
        public virtual InstRecaudos LstIRecaudos { get; set; }
    }
}
