//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoapCorrBanDet
    {
        public short Id { get; set; }
        public short IdLstSoapCarrBan { get; set; }
        public string Descripcion { get; set; }
        public string SoapLiris { get; set; }
        public string XsdLiris { get; set; }
        public string SoapRedActiva { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Estado { get; set; }
        public string XslConvert { get; set; }
    
        public virtual SoapCorrBan LstSoapCorrBan { get; set; }
    }
}
