//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LirisLibCorrBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VieReqsWF
    {
        public string Trama { get; set; }
        public string Cuenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public string Corresponsal { get; set; }
        public string CodigoEmpresa { get; set; }
        public int SecuencialSara { get; set; }
        public int Secuencial { get; set; }
        public string Canal { get; set; }
        public string Terminal { get; set; }
        public string Operador { get; set; }
        public int IdRecaudacion { get; set; }
        public short IdIRecaudos { get; set; }
        public short IdTipoCorrBan { get; set; }
        public string CodigoCliente { get; set; }
        public string Estado { get; set; }
        public short TipoRecaudo { get; set; }
        public string IdCaja { get; set; }
        public Nullable<short> WFEstado { get; set; }
        public short WFTipo { get; set; }
        public int WFPkgNo { get; set; }
    }
}
