//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.WSIntegracion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSIntegracion.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IntegrationDelivery", ReplyAction="http://tempuri.org/IService1/IntegrationDeliveryResponse")]
        string IntegrationDelivery(string requerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IntegrationDelivery", ReplyAction="http://tempuri.org/IService1/IntegrationDeliveryResponse")]
        System.Threading.Tasks.Task<string> IntegrationDeliveryAsync(string requerimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : POS.WSIntegracion.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<POS.WSIntegracion.IService1>, POS.WSIntegracion.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string IntegrationDelivery(string requerimiento) {
            return base.Channel.IntegrationDelivery(requerimiento);
        }
        
        public System.Threading.Tasks.Task<string> IntegrationDeliveryAsync(string requerimiento) {
            return base.Channel.IntegrationDeliveryAsync(requerimiento);
        }
    }
}
