<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="ReceptionSdk" Version="1.8.2" />
    <PackageReference Include="ReceptionSdk.csproj" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ReceptionSdk">
      <HintPath>..\..\..\Users\sescobar\.nuget\packages\receptionsdk.csproj\1.0.0\ReceptionSdkTest\bin\Release\ReceptionSdk.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
