//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.BroadNetWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BroadNetWebService.wsrecargasSoap")]
    public interface wsrecargasSoap {
        
        // CODEGEN: Generating message contract since element name tipoTransaccion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/peticionRequerimiento", ReplyAction="*")]
        POS.BroadNetWebService.peticionRequerimientoResponse peticionRequerimiento(POS.BroadNetWebService.peticionRequerimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/peticionRequerimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<POS.BroadNetWebService.peticionRequerimientoResponse> peticionRequerimientoAsync(POS.BroadNetWebService.peticionRequerimientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class peticionRequerimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="peticionRequerimiento", Namespace="http://tempuri.org/", Order=0)]
        public POS.BroadNetWebService.peticionRequerimientoRequestBody Body;
        
        public peticionRequerimientoRequest() {
        }
        
        public peticionRequerimientoRequest(POS.BroadNetWebService.peticionRequerimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class peticionRequerimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoTransaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigoProceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string proveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string servicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string autorizacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string referencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string lote;
        
        public peticionRequerimientoRequestBody() {
        }
        
        public peticionRequerimientoRequestBody(string tipoTransaccion, string codigoProceso, string monto, string cajero, string clave, string tid, string mid, string proveedor, string servicio, string cuenta, string autorizacion, string referencia, string lote) {
            this.tipoTransaccion = tipoTransaccion;
            this.codigoProceso = codigoProceso;
            this.monto = monto;
            this.cajero = cajero;
            this.clave = clave;
            this.tid = tid;
            this.mid = mid;
            this.proveedor = proveedor;
            this.servicio = servicio;
            this.cuenta = cuenta;
            this.autorizacion = autorizacion;
            this.referencia = referencia;
            this.lote = lote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class peticionRequerimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="peticionRequerimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS.BroadNetWebService.peticionRequerimientoResponseBody Body;
        
        public peticionRequerimientoResponse() {
        }
        
        public peticionRequerimientoResponse(POS.BroadNetWebService.peticionRequerimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class peticionRequerimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string peticionRequerimientoResult;
        
        public peticionRequerimientoResponseBody() {
        }
        
        public peticionRequerimientoResponseBody(string peticionRequerimientoResult) {
            this.peticionRequerimientoResult = peticionRequerimientoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsrecargasSoapChannel : POS.BroadNetWebService.wsrecargasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsrecargasSoapClient : System.ServiceModel.ClientBase<POS.BroadNetWebService.wsrecargasSoap>, POS.BroadNetWebService.wsrecargasSoap {
        
        public wsrecargasSoapClient() {
        }
        
        public wsrecargasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsrecargasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsrecargasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsrecargasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS.BroadNetWebService.peticionRequerimientoResponse POS.BroadNetWebService.wsrecargasSoap.peticionRequerimiento(POS.BroadNetWebService.peticionRequerimientoRequest request) {
            return base.Channel.peticionRequerimiento(request);
        }
        
        public string peticionRequerimiento(string tipoTransaccion, string codigoProceso, string monto, string cajero, string clave, string tid, string mid, string proveedor, string servicio, string cuenta, string autorizacion, string referencia, string lote) {
            POS.BroadNetWebService.peticionRequerimientoRequest inValue = new POS.BroadNetWebService.peticionRequerimientoRequest();
            inValue.Body = new POS.BroadNetWebService.peticionRequerimientoRequestBody();
            inValue.Body.tipoTransaccion = tipoTransaccion;
            inValue.Body.codigoProceso = codigoProceso;
            inValue.Body.monto = monto;
            inValue.Body.cajero = cajero;
            inValue.Body.clave = clave;
            inValue.Body.tid = tid;
            inValue.Body.mid = mid;
            inValue.Body.proveedor = proveedor;
            inValue.Body.servicio = servicio;
            inValue.Body.cuenta = cuenta;
            inValue.Body.autorizacion = autorizacion;
            inValue.Body.referencia = referencia;
            inValue.Body.lote = lote;
            POS.BroadNetWebService.peticionRequerimientoResponse retVal = ((POS.BroadNetWebService.wsrecargasSoap)(this)).peticionRequerimiento(inValue);
            return retVal.Body.peticionRequerimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POS.BroadNetWebService.peticionRequerimientoResponse> POS.BroadNetWebService.wsrecargasSoap.peticionRequerimientoAsync(POS.BroadNetWebService.peticionRequerimientoRequest request) {
            return base.Channel.peticionRequerimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<POS.BroadNetWebService.peticionRequerimientoResponse> peticionRequerimientoAsync(string tipoTransaccion, string codigoProceso, string monto, string cajero, string clave, string tid, string mid, string proveedor, string servicio, string cuenta, string autorizacion, string referencia, string lote) {
            POS.BroadNetWebService.peticionRequerimientoRequest inValue = new POS.BroadNetWebService.peticionRequerimientoRequest();
            inValue.Body = new POS.BroadNetWebService.peticionRequerimientoRequestBody();
            inValue.Body.tipoTransaccion = tipoTransaccion;
            inValue.Body.codigoProceso = codigoProceso;
            inValue.Body.monto = monto;
            inValue.Body.cajero = cajero;
            inValue.Body.clave = clave;
            inValue.Body.tid = tid;
            inValue.Body.mid = mid;
            inValue.Body.proveedor = proveedor;
            inValue.Body.servicio = servicio;
            inValue.Body.cuenta = cuenta;
            inValue.Body.autorizacion = autorizacion;
            inValue.Body.referencia = referencia;
            inValue.Body.lote = lote;
            return ((POS.BroadNetWebService.wsrecargasSoap)(this)).peticionRequerimientoAsync(inValue);
        }
    }
}
