//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=[ipserver];Initial Catalog=DynamicsAx1;Persist Security Info=True;Use" +
            "r ID=app_pos;Password=L1r1$PO$@pp892126565V01;App=POS")]
        public string CONECTA_AX {
            get {
                return ((string)(this["CONECTA_AX"]));
            }
            set {
                this["CONECTA_AX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.liris.com.ec")]
        public string SMTP_SERVER {
            get {
                return ((string)(this["SMTP_SERVER"]));
            }
            set {
                this["SMTP_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SMTP_PORT {
            get {
                return ((int)(this["SMTP_PORT"]));
            }
            set {
                this["SMTP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SMTP_USESSL {
            get {
                return ((bool)(this["SMTP_USESSL"]));
            }
            set {
                this["SMTP_USESSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POS")]
        public string MAILERROR_ALIAS {
            get {
                return ((string)(this["MAILERROR_ALIAS"]));
            }
            set {
                this["MAILERROR_ALIAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POS ERROR")]
        public string MAILERROR_MOTIVO {
            get {
                return ((string)(this["MAILERROR_MOTIVO"]));
            }
            set {
                this["MAILERROR_MOTIVO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aplicacion@liris.com.ec")]
        public string MAILERROR_FROM {
            get {
                return ((string)(this["MAILERROR_FROM"]));
            }
            set {
                this["MAILERROR_FROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Log\\POSInserts\\|yyyy-|MM-|dd.txt")]
        public string EF_LOG {
            get {
                return ((string)(this["EF_LOG"]));
            }
            set {
                this["EF_LOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string EFLOG_PATH {
            get {
                return ((string)(this["EFLOG_PATH"]));
            }
            set {
                this["EFLOG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\SRV-POS\\Retenciones\\Blanco.png")]
        public string RETENCION_PATHLOGO {
            get {
                return ((string)(this["RETENCION_PATHLOGO"]));
            }
            set {
                this["RETENCION_PATHLOGO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbmail")]
        public string SMTP_USER {
            get {
                return ((string)(this["SMTP_USER"]));
            }
            set {
                this["SMTP_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@KeW(r_k=X7(")]
        public string SMTP_PASS {
            get {
                return ((string)(this["SMTP_PASS"]));
            }
            set {
                this["SMTP_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("devteam@liris.com.ec")]
        public string MAILERROR_DESTINO {
            get {
                return ((string)(this["MAILERROR_DESTINO"]));
            }
            set {
                this["MAILERROR_DESTINO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("devteam@liris.com.ec")]
        public string MAILERROR_CC {
            get {
                return ((string)(this["MAILERROR_CC"]));
            }
            set {
                this["MAILERROR_CC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Log\\POSConexiones.txt")]
        public string CONEXION_PATH {
            get {
                return ((string)(this["CONEXION_PATH"]));
            }
            set {
                this["CONEXION_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\srvatila\\Shares\\Compartido\\Conexiones\\POSConexiones.txt")]
        public string CONEXION_PATH_REMOTO {
            get {
                return ((string)(this["CONEXION_PATH_REMOTO"]));
            }
            set {
                this["CONEXION_PATH_REMOTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Log\\POSImg")]
        public string PATH_IMG {
            get {
                return ((string)(this["PATH_IMG"]));
            }
            set {
                this["PATH_IMG"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          AL OPRIMIR ACEPTAR:

          DECLARO QUE HE LEIDO Y ACEPTO LA TOTALIDAD DE LAS CONDICIONES DE USO DEL SISTEMA.

          DECLARO QUE ACEPTO RECIBIR LA SUMA DETALLADA EN LA PARTE SUPERIOR, CORRESPONDIENTE AL MONTO PARA SUELTOS QUE ME COMPROMETO A DEVOLVER  AL CIERRE Y CUADRE DE LA CAJA, SUMADO AL TOTAL DE INGRESOS DEL DÍA Y ASUMO PERSONALMENTE LA RESPONSABILIDAD POR FALTANTES DE DINERO BAJO MI CUSTODIA.
        ")]
        public string MENSAJE_CAJA {
            get {
                return ((string)(this["MENSAJE_CAJA"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://[ipserver]:8000/")]
        public string ROOT_URL {
            get {
                return ((string)(this["ROOT_URL"]));
            }
            set {
                this["ROOT_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://[ipserver]:8000/webrequests/")]
        public string ROOT_URL_GENERAL {
            get {
                return ((string)(this["ROOT_URL_GENERAL"]));
            }
            set {
                this["ROOT_URL_GENERAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=[ipserver];Initial Catalog=Marketing;Persist Security Info=True;User " +
            "ID=app_pos;Password=L1r1$PO$@pp892126565V01;")]
        public string CONECTA_MKT {
            get {
                return ((string)(this["CONECTA_MKT"]));
            }
            set {
                this["CONECTA_MKT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POS Dynamics AX 2025")]
        public string TituloApp {
            get {
                return ((string)(this["TituloApp"]));
            }
            set {
                this["TituloApp"] = value;
            }
        }
    }
}
